import type { TipTapDocument } from '../../types/topic';
import type { ClinicalApproach, ComplementaryStudy, DifferentialDiagnosisItem, ReasoningItem } from './clinicalApproachTypes';
import { validateDecisionTree } from './decisionTreeValidation';

type TextBlock = { kind: 'paragraph' | 'heading'; text: string } | { kind: 'bullet'; items: string[] };

const textNode = (text: string) => ({ type: 'text', text });
const richText = (...blocks: TextBlock[]): TipTapDocument => ({
  type: 'doc',
  content: blocks.map((block) => block.kind === 'bullet'
    ? { type: 'bulletList', content: block.items.map((item) => ({ type: 'listItem', content: [{ type: 'paragraph', content: [textNode(item)] }] })) }
    : { type: block.kind, ...(block.kind === 'heading' ? { attrs: { level: 3 } } : {}), content: [textNode(block.text)] })
});
const paragraph = (text: string): TipTapDocument => richText({ kind: 'paragraph', text });
const stableId = (group: number, index: number) => `${group.toString().padStart(8, '0')}-0000-4000-8000-${index.toString().padStart(12, '0')}`;
const reasoning = (group: number, entries: Array<[string, string, string]>): ReasoningItem[] => entries.map(([title, content, whyItMatters], index) => ({ id: stableId(group, index + 1), title, content: paragraph(content), whyItMatters: paragraph(whyItMatters) }));
const differentials = (group: number, entries: Array<[string, string]>): DifferentialDiagnosisItem[] => entries.map(([title, explanation], index) => ({ id: stableId(group, index + 1), title, explanation: paragraph(explanation) }));
const studies = (entries: Array<[string, string, string, string]>): ComplementaryStudy[] => entries.map(([name, whenToOrder, targetFinding, interpretation], index) => ({ id: stableId(6, index + 1), name, whenToOrder: paragraph(whenToOrder), targetFinding: paragraph(targetFinding), interpretation: paragraph(interpretation) }));

export const DYSPNEA_APPROACH_TITLE = 'Disnea';

export function createDyspneaClinicalApproach(userId: string): ClinicalApproach {
  const timestamp = new Date().toISOString();
  const approach: ClinicalApproach = {
    id: crypto.randomUUID(), userId, title: DYSPNEA_APPROACH_TITLE,
    description: 'Abordaje inicial del paciente con disnea aguda o subaguda, orientado a evaluar estabilidad, reconocer causas respiratorias y cardiovasculares potencialmente mortales, identificar el mecanismo predominante, seleccionar estudios y definir tratamiento, reevaluación y disposición.',
    categoryId: null, category: null, createdAt: timestamp, updatedAt: timestamp, status: 'complete',
    content: {
      version: 1,
      presentation: richText(
        { kind: 'paragraph', text: 'La disnea es la percepción subjetiva de dificultad respiratoria y puede originarse en enfermedades respiratorias, cardiovasculares, metabólicas, hematológicas, neuromusculares, tóxicas o psicógenas.' },
        { kind: 'paragraph', text: 'El primer objetivo no es identificar inmediatamente el diagnóstico definitivo, sino establecer:' },
        { kind: 'bullet', items: ['si existe insuficiencia respiratoria', 'si el paciente está hemodinámicamente estable', 'si requiere soporte ventilatorio inmediato', 'si hay una causa potencialmente mortal y tiempo-dependiente', 'cuál parece ser el mecanismo predominante', 'qué estudios deben realizarse sin retrasar el tratamiento'] },
        { kind: 'paragraph', text: 'La severidad subjetiva del síntoma no siempre se correlaciona con la gravedad fisiológica. Pacientes muy graves pueden presentar inicialmente escasos signos y otros con intensa sensación disneica pueden mantener intercambio gaseoso adecuado.' }
      ),
      initialAssessment: richText(
        { kind: 'paragraph', text: 'Evaluar de inmediato:' },
        { kind: 'bullet', items: ['vía aérea', 'frecuencia y patrón respiratorio', 'trabajo respiratorio', 'capacidad para hablar', 'uso de músculos accesorios', 'tiraje', 'presencia de estridor', 'saturación de oxígeno', 'frecuencia cardíaca', 'presión arterial', 'temperatura', 'estado de conciencia', 'perfusión periférica'] },
        { kind: 'paragraph', text: 'Buscar signos de insuficiencia respiratoria o agotamiento:' },
        { kind: 'bullet', items: ['alteración del sensorio', 'incapacidad para hablar frases', 'bradipnea', 'apnea', 'respiración paradójica', 'fatiga progresiva', 'hipoxemia significativa', 'cianosis', 'silencio auscultatorio', 'estridor importante', 'inestabilidad hemodinámica'] },
        { kind: 'paragraph', text: 'Ante compromiso grave, estabilización y diagnóstico deben ocurrir simultáneamente.' },
        { kind: 'paragraph', text: 'Según la situación puede requerirse:' },
        { kind: 'bullet', items: ['posición adecuada', 'monitorización', 'oxígeno', 'ventilación no invasiva', 'ventilación invasiva', 'broncodilatadores', 'tratamiento de edema agudo de pulmón', 'tratamiento de anafilaxia', 'descompresión torácica', 'anticoagulación o reperfusión en escenarios seleccionados', 'antibióticos', 'tratamiento específico de la causa'] },
        { kind: 'paragraph', text: 'No utilizar únicamente la saturación para decidir gravedad. La clínica respiratoria y la evolución son fundamentales.' }
      ),
      lifeThreats: richText(
        { kind: 'paragraph', text: 'Las principales causas potencialmente mortales o tiempo-dependientes de disnea que deben reconocerse precozmente incluyen:' },
        { kind: 'bullet', items: ['obstrucción aguda de vía aérea', 'anafilaxia', 'neumotórax a tensión', 'embolia pulmonar de alto riesgo', 'edema agudo de pulmón / insuficiencia cardíaca aguda', 'síndrome coronario agudo con insuficiencia cardíaca o equivalente anginoso', 'asma grave o casi fatal', 'exacerbación grave de EPOC con insuficiencia respiratoria', 'neumonía grave / sepsis', 'síndrome de distrés respiratorio agudo', 'taponamiento cardíaco', 'intoxicación por monóxido de carbono', 'metahemoglobinemia', 'acidosis metabólica grave'] },
        { kind: 'heading', text: 'Obstrucción aguda de vía aérea' }, { kind: 'paragraph', text: 'Considerar ante estridor, imposibilidad para hablar, voz alterada, dificultad inspiratoria, disminución brusca del flujo aéreo o deterioro rápido. Puede requerir manejo avanzado inmediato de la vía aérea.' },
        { kind: 'heading', text: 'Anafilaxia' }, { kind: 'paragraph', text: 'Puede combinar disnea, broncoespasmo, edema de vía aérea, urticaria, síntomas gastrointestinales e hipotensión. La ausencia de manifestaciones cutáneas no la excluye.' },
        { kind: 'heading', text: 'Neumotórax a tensión' }, { kind: 'paragraph', text: 'Sospechar ante disnea súbita, dolor torácico, disminución unilateral del murmullo vesicular, compromiso hemodinámico y signos de presión intratorácica elevada. El tratamiento no debe esperar confirmación radiológica cuando la sospecha clínica es alta y el paciente está inestable.' },
        { kind: 'heading', text: 'Embolia pulmonar de alto riesgo' }, { kind: 'paragraph', text: 'Considerar ante disnea súbita, síncope, dolor torácico, taquicardia, hipoxemia, hipotensión o signos de sobrecarga del ventrículo derecho, especialmente en pacientes con factores tromboembólicos.' },
        { kind: 'heading', text: 'Edema agudo de pulmón' }, { kind: 'paragraph', text: 'Puede presentarse con disnea intensa, ortopnea, crepitantes, hipoxemia, hipertensión o hipotensión y signos de congestión. Identificar precipitantes y necesidad de soporte ventilatorio.' },
        { kind: 'heading', text: 'Asma grave' }, { kind: 'paragraph', text: 'Buscar dificultad respiratoria intensa, uso de músculos accesorios, incapacidad para hablar, alteración del sensorio, disminución marcada de ruidos respiratorios y mala respuesta al tratamiento inicial.' },
        { kind: 'heading', text: 'EPOC grave' }, { kind: 'paragraph', text: 'Evaluar hipercapnia, alteración del sensorio, fatiga respiratoria, acidosis y necesidad de ventilación no invasiva o invasiva.' },
        { kind: 'heading', text: 'Neumonía grave / sepsis' }, { kind: 'paragraph', text: 'Considerar ante infección respiratoria asociada a hipoxemia, hipotensión, deterioro del sensorio o disfunción orgánica.' },
        { kind: 'heading', text: 'Taponamiento cardíaco' }, { kind: 'paragraph', text: 'Puede presentarse con disnea, hipotensión, taquicardia, ingurgitación yugular y signos de bajo gasto.' },
        { kind: 'heading', text: 'Intoxicaciones y dishemoglobinemias' }, { kind: 'paragraph', text: 'El monóxido de carbono puede producir disnea, cefalea, mareos y alteración neurológica con pulsioximetría aparentemente normal. La metahemoglobinemia puede producir cianosis e hipoxemia aparente poco corregible con oxígeno.' },
        { kind: 'heading', text: 'Acidosis metabólica grave' }, { kind: 'paragraph', text: 'La taquipnea puede ser una respuesta compensatoria a cetoacidosis, sepsis, insuficiencia renal u otras causas metabólicas y no necesariamente una enfermedad pulmonar primaria.' }
      ),
      anamnesis: reasoning(1, [
        ['Inicio y velocidad de instauración', 'Preguntar cuándo comenzó la disnea y si se instauró en segundos, minutos, horas, días o semanas.', 'La disnea súbita orienta hacia embolia pulmonar, neumotórax, edema agudo de pulmón, arritmia, anafilaxia u obstrucción de vía aérea, mientras que una evolución más lenta sugiere infecciones, insuficiencia cardíaca progresiva, anemia u otras causas.'],
        ['Situación de aparición', 'Determinar si comenzó en reposo, durante ejercicio, durante el sueño, tras exposición, luego de una comida, medicamento, ejercicio o procedimiento.', 'El contexto de inicio puede orientar hacia enfermedad cardíaca, anafilaxia, broncoespasmo, aspiración, embolia o exposición tóxica.'],
        ['Disnea de esfuerzo', 'Preguntar qué nivel de actividad desencadena los síntomas y comparar con la capacidad funcional habitual.', 'La reducción reciente de la tolerancia al ejercicio puede ser manifestación temprana de insuficiencia cardíaca, enfermedad pulmonar, anemia o enfermedad sistémica.'],
        ['Ortopnea', 'Preguntar si la dificultad respiratoria aparece o empeora al acostarse y cuántas almohadas necesita para dormir.', 'Orienta especialmente hacia congestión pulmonar e insuficiencia cardíaca, aunque no es exclusiva de ella.'],
        ['Disnea paroxística nocturna', 'Preguntar si se despierta durante la noche con sensación intensa de falta de aire que mejora al sentarse o incorporarse.', 'Es un dato clásico de congestión pulmonar e insuficiencia cardíaca.'],
        ['Dolor torácico asociado', 'Preguntar por dolor opresivo, pleurítico, súbito, irradiado o relacionado al esfuerzo.', 'Puede orientar hacia síndrome coronario agudo, embolia pulmonar, neumotórax, pericarditis, disección aórtica o causas musculoesqueléticas.'],
        ['Tos y expectoración', 'Preguntar por tos seca o productiva, cantidad y características del esputo.', 'Puede orientar hacia infección respiratoria, edema pulmonar, exacerbación obstructiva u otras enfermedades de vía aérea.'],
        ['Fiebre y síntomas infecciosos', 'Preguntar por fiebre, escalofríos, síntomas respiratorios altos, contacto con enfermos y evolución infecciosa.', 'Aumenta la probabilidad de neumonía, infección viral, sepsis u otras infecciones respiratorias.'],
        ['Sibilancias y antecedentes obstructivos', 'Preguntar por episodios previos de sibilancias, asma, EPOC y respuesta a broncodilatadores.', 'Ayuda a identificar broncoespasmo como mecanismo predominante y valorar la gravedad respecto de episodios previos.'],
        ['Hemoptisis', 'Preguntar por expectoración con sangre y cuantificar aproximadamente su magnitud.', 'Puede aparecer en embolia pulmonar, infecciones, neoplasias, bronquiectasias, edema pulmonar y otras enfermedades.'],
        ['Edema y aumento de peso', 'Preguntar por edema periférico, aumento reciente de peso y distensión abdominal.', 'Sugiere retención hidrosalina y posible insuficiencia cardíaca.'],
        ['Palpitaciones y síncope', 'Preguntar por palpitaciones, mareos, presíncope o síncope.', 'Puede orientar hacia arritmias, embolia pulmonar de alto riesgo, enfermedad cardíaca estructural o hipoxemia significativa.'],
        ['Factores de riesgo tromboembólico', 'Preguntar por inmovilización, cirugía reciente, neoplasia, embarazo/puerperio, tratamiento hormonal, trombosis previa y viajes prolongados.', 'Aumentan la probabilidad pretest de embolia pulmonar.'],
        ['Antecedentes cardiovasculares', 'Preguntar por insuficiencia cardíaca, cardiopatía isquémica, hipertensión, valvulopatías, arritmias y enfermedad estructural.', 'Incrementan la probabilidad de origen cardiovascular de la disnea.'],
        ['Antecedentes respiratorios', 'Preguntar por asma, EPOC, fibrosis pulmonar, tuberculosis, enfermedad intersticial, neumotórax y cirugías pulmonares.', 'Permiten interpretar la disnea respecto de la función basal y orientar etiologías.'],
        ['Exposiciones', 'Preguntar por humo, incendio, gases, productos químicos, polvo, alérgenos y exposiciones ocupacionales.', 'Puede revelar intoxicación, lesión inhalatoria, broncoespasmo o enfermedad pulmonar relacionada con exposición.'],
        ['Medicaciones', 'Preguntar por diuréticos, betabloqueantes, broncodilatadores, opioides, sedantes, anticoagulantes y medicamentos nuevos.', 'La medicación puede explicar descompensaciones, toxicidad, depresión respiratoria o modificar la probabilidad de determinados diagnósticos.'],
        ['Anemia o sangrado', 'Preguntar por sangrado digestivo, menstrual, quirúrgico u otras pérdidas y por antecedentes de anemia.', 'La reducción de la capacidad de transporte de oxígeno puede producir disnea incluso sin enfermedad pulmonar primaria.']
      ]),
      physicalExam: reasoning(2, [
        ['Apariencia general y capacidad para hablar', 'Evaluar ansiedad, posición, uso de frases completas, diaforesis, agitación, somnolencia y signos de agotamiento.', 'La incapacidad para hablar frases completas, el deterioro del sensorio y el agotamiento son signos de gravedad.'],
        ['Frecuencia y patrón respiratorio', 'Evaluar frecuencia, profundidad, regularidad, respiración paradójica y patrones respiratorios anormales.', 'Taquipnea puede indicar hipoxemia, acidosis, infección o compromiso cardiopulmonar; bradipnea en un paciente fatigado puede indicar deterioro inminente.'],
        ['Trabajo respiratorio', 'Buscar tiraje, uso de músculos accesorios, aleteo nasal y retracciones.', 'Refleja aumento de la carga ventilatoria y puede preceder al agotamiento.'],
        ['Saturación y signos de hipoxemia', 'Evaluar saturación de oxígeno, coloración de piel y mucosas y respuesta inicial al oxígeno cuando corresponda.', 'Permite detectar alteración del intercambio gaseoso, aunque una saturación aparentemente normal no excluye monóxido de carbono ni otras causas de disnea.'],
        ['Auscultación pulmonar', 'Buscar sibilancias, crepitantes, roncus, estridor, disminución unilateral del murmullo vesicular o silencio auscultatorio.', 'Los hallazgos pueden orientar hacia broncoespasmo, edema pulmonar, neumonía, neumotórax u obstrucción de vía aérea.'],
        ['Expansión torácica y percusión', 'Comparar expansión de ambos hemitórax y realizar percusión cuando aporte información.', 'Asimetría y cambios en la sonoridad pueden apoyar neumotórax, derrame u otras alteraciones pleurales.'],
        ['Signos cardiovasculares', 'Evaluar frecuencia y ritmo cardíaco, presión arterial, ruidos cardíacos y signos de bajo gasto.', 'Arritmias, cardiopatía aguda e insuficiencia cardíaca son causas frecuentes y potencialmente graves de disnea.'],
        ['Ingurgitación yugular', 'Buscar elevación de la presión venosa yugular cuando la técnica y el contexto lo permitan.', 'Puede orientar hacia congestión derecha, insuficiencia cardíaca, embolia pulmonar de riesgo o taponamiento.'],
        ['Edema periférico', 'Evaluar edema en miembros inferiores y signos de congestión sistémica.', 'Apoya insuficiencia cardíaca y sobrecarga de volumen.'],
        ['Signos de trombosis venosa profunda', 'Buscar edema unilateral, aumento de diámetro, dolor o cambios locales compatibles.', 'Aumentan la sospecha de enfermedad tromboembólica.'],
        ['Vía aérea superior', 'Buscar estridor, edema de labios o lengua, urticaria, voz apagada y dificultad para manejar secreciones.', 'Permite reconocer obstrucción de vía aérea o anafilaxia que pueden progresar rápidamente.'],
        ['Estado neurológico', 'Evaluar orientación, agitación, somnolencia y nivel de conciencia.', 'Alteraciones pueden reflejar hipoxemia, hipercapnia, shock, intoxicación o fatiga respiratoria.']
      ]),
      differentialDiagnosis: {
        lifeThreatening: differentials(3, [
          ['Obstrucción aguda de vía aérea', 'Puede deteriorar rápidamente la ventilación y requerir manejo inmediato de vía aérea.'], ['Anafilaxia', 'Puede producir edema de vía aérea, broncoespasmo y shock. La adrenalina intramuscular es el tratamiento inicial fundamental cuando está indicada.'], ['Neumotórax a tensión', 'Puede producir insuficiencia respiratoria y shock obstructivo y requiere descompresión urgente ante alta sospecha clínica.'], ['Embolia pulmonar de alto riesgo', 'Puede producir insuficiencia ventricular derecha, hipotensión, shock o paro cardíaco.'], ['Edema agudo de pulmón', 'Puede generar hipoxemia grave y necesidad urgente de soporte ventilatorio y tratamiento de la causa.'], ['Asma grave o casi fatal', 'La obstrucción severa puede evolucionar a agotamiento, hipercapnia, silencio auscultatorio y paro respiratorio.'], ['Exacerbación grave de EPOC', 'Puede causar insuficiencia respiratoria hipercápnica y requerir soporte ventilatorio.'], ['Neumonía grave / sepsis', 'Puede producir hipoxemia, shock y falla orgánica.'], ['Síndrome de distrés respiratorio agudo', 'Produce hipoxemia grave secundaria a lesión pulmonar difusa y requiere manejo intensivo.'], ['Taponamiento cardíaco', 'Puede producir shock obstructivo y requiere diagnóstico y tratamiento urgente.'], ['Síndrome coronario agudo complicado', 'La isquemia miocárdica puede presentarse como disnea y producir edema pulmonar, arritmias o shock.'], ['Intoxicación por monóxido de carbono', 'Puede producir hipoxia tisular grave con pulsioximetría engañosamente normal.'], ['Metahemoglobinemia', 'Puede causar cianosis e hipoxia funcional con respuesta limitada al oxígeno convencional.'], ['Acidosis metabólica grave', 'La respiración rápida y profunda puede ser compensatoria y señalar una emergencia metabólica.']
        ]),
        common: differentials(4, [
          ['Asma', 'La obstrucción bronquial reversible puede causar disnea, sibilancias y espiración prolongada.'], ['Exacerbación de EPOC', 'Suele asociar aumento de disnea, tos o expectoración respecto del estado basal.'], ['Insuficiencia cardíaca', 'La congestión pulmonar puede producir disnea de esfuerzo, ortopnea y crepitantes.'], ['Neumonía', 'Puede presentarse con fiebre, tos, hipoxemia y hallazgos focales.'], ['Infección respiratoria viral', 'Puede causar disnea por compromiso de vía aérea o parénquima pulmonar.'], ['Bronquitis aguda', 'La inflamación bronquial suele producir tos y puede acompañarse de sensación disneica.'], ['Derrame pleural', 'Puede limitar la ventilación y producir disminución del murmullo vesicular.'], ['Anemia', 'Reduce el transporte de oxígeno y puede causar disnea de esfuerzo o en reposo.'], ['Ansiedad / hiperventilación', 'Puede generar intensa sensación disneica, pero requiere excluir razonablemente causas orgánicas relevantes.'], ['Desacondicionamiento físico', 'Puede manifestarse como intolerancia al esfuerzo sin enfermedad cardiopulmonar aguda.']
        ]),
        contextual: differentials(5, [
          ['Enfermedad pulmonar intersticial', 'Puede alterar la difusión y producir disnea progresiva.'], ['Fibrosis pulmonar', 'Suele causar disnea crónica progresiva y crepitantes inspiratorios.'], ['Hipertensión pulmonar', 'Puede producir disnea de esfuerzo, síncope y signos de sobrecarga derecha.'], ['Enfermedad valvular', 'Las valvulopatías pueden ocasionar congestión o bajo gasto.'], ['Arritmias', 'Las frecuencias inadecuadas pueden reducir el gasto cardíaco y causar disnea.'], ['Pericarditis', 'Puede asociar dolor pleurítico y derrame pericárdico.'], ['Derrame pericárdico', 'Puede limitar el llenado cardíaco y, si progresa, producir taponamiento.'], ['Miocarditis', 'Puede causar disfunción ventricular, arritmias y disnea.'], ['Neoplasia pulmonar', 'Puede causar obstrucción, derrame, infección o pérdida de parénquima funcional.'], ['Derrame pleural maligno', 'Puede producir disnea progresiva por restricción ventilatoria.'], ['Tuberculosis', 'Puede comprometer parénquima o pleura y producir síntomas respiratorios sistémicos.'], ['Enfermedad neuromuscular', 'La debilidad ventilatoria puede causar hipoventilación e insuficiencia respiratoria.'], ['Debilidad diafragmática', 'Puede causar ortopnea e hipoventilación, especialmente en decúbito.'], ['Obesidad / hipoventilación', 'Puede generar hipoventilación crónica y descompensación hipercápnica.'], ['Síndrome de apnea obstructiva del sueño', 'Puede asociarse a hipoxemia nocturna y comorbilidad cardiopulmonar.'], ['Cetoacidosis diabética', 'La respiración profunda y rápida compensa la acidosis metabólica.'], ['Insuficiencia renal con sobrecarga de volumen', 'Puede causar edema pulmonar y acidosis.'], ['Acidosis metabólica', 'Produce hiperventilación compensatoria cuya causa debe identificarse.'], ['Intoxicaciones', 'Pueden alterar el transporte de oxígeno, la ventilación o el metabolismo.'], ['Dolor o restricción de pared torácica', 'Puede limitar la expansión torácica y generar sensación de falta de aire.']
        ])
      },
      complementaryStudies: studies([
        ['Oximetría de pulso', 'Prácticamente en toda disnea aguda o clínicamente relevante.', 'Hipoxemia y tendencia de la saturación.', 'Debe interpretarse junto con la clínica. Puede ser engañosa en intoxicación por monóxido de carbono y ciertas dishemoglobinemias.'],
        ['Gasometría arterial o venosa', 'Ante insuficiencia respiratoria, sospecha de hipercapnia, alteración del sensorio, acidosis o enfermedad obstructiva grave.', 'pH, CO2, oxigenación y trastornos ácido-base.', 'La gasometría permite valorar ventilación y equilibrio ácido-base. La arterial es necesaria cuando se requiere una valoración precisa de oxigenación.'],
        ['ECG de 12 derivaciones', 'En disnea aguda cuando existe posibilidad de causa cardiovascular, arritmia o embolia pulmonar.', 'Isquemia, arritmias, alteraciones de conducción y signos indirectos de sobrecarga derecha.', 'Puede revelar un síndrome coronario agudo o arritmia y aportar datos en embolia pulmonar, aunque un ECG normal no la excluye.'],
        ['Radiografía de tórax', 'En gran parte de los pacientes con disnea aguda cuando se sospecha patología cardiopulmonar.', 'Infiltrados, edema pulmonar, derrame pleural, neumotórax, cardiomegalia y otros hallazgos.', 'Es útil para múltiples diagnósticos, pero una radiografía normal no excluye embolia pulmonar, asma ni enfermedad temprana.'],
        ['POCUS cardiopulmonar', 'Cuando esté disponible y pueda responder preguntas clínicas concretas en disnea aguda.', 'Líneas B, derrame pleural, neumotórax, función ventricular, dilatación de ventrículo derecho, derrame pericárdico y volumen intravascular en contexto.', 'Puede acelerar la diferenciación entre causas cardíacas, pulmonares y obstructivas, pero debe integrarse con la evaluación clínica.'],
        ['Hemograma', 'Ante sospecha de infección, anemia, sangrado o enfermedad sistémica.', 'Leucocitosis, leucopenia, anemia y otras alteraciones hematológicas.', 'La anemia puede explicar o agravar disnea y los leucocitos deben interpretarse dentro del contexto clínico.'],
        ['Función renal e ionograma', 'Ante insuficiencia cardíaca, tratamiento con diuréticos, enfermedad sistémica, sepsis o trastornos metabólicos.', 'Función renal y alteraciones electrolíticas.', 'Ayuda a valorar gravedad, causas precipitantes y seguridad del tratamiento.'],
        ['Troponina cardíaca', 'Ante sospecha de síndrome coronario agudo, insuficiencia cardíaca aguda, embolia pulmonar de riesgo u otra lesión miocárdica.', 'Evidencia bioquímica de lesión miocárdica.', 'Una elevación no es específica de infarto y debe interpretarse con clínica, ECG y dinámica temporal.'],
        ['Péptidos natriuréticos', 'Cuando exista incertidumbre diagnóstica respecto de insuficiencia cardíaca como causa de disnea.', 'BNP o NT-proBNP elevados.', 'Valores bajos pueden ayudar a hacer menos probable insuficiencia cardíaca aguda, mientras que valores altos requieren interpretación según edad, función renal y contexto.'],
        ['Dímero D', 'En pacientes con probabilidad clínica baja o intermedia de embolia pulmonar cuando un resultado negativo pueda evitar imágenes.', 'Ausencia de elevación significativa según estrategia diagnóstica utilizada.', 'No debe usarse indiscriminadamente. Un valor positivo es inespecífico y no confirma embolia pulmonar.'],
        ['Angio-TC pulmonar', 'Ante sospecha de embolia pulmonar cuando la probabilidad clínica y la estrategia diagnóstica indiquen imagen.', 'Defectos de repleción compatibles con tromboembolismo pulmonar y signos asociados.', 'Es el estudio de referencia habitual para confirmar embolia pulmonar en muchos escenarios clínicos.'],
        ['Ecocardiograma', 'Ante sospecha de insuficiencia cardíaca, valvulopatía, taponamiento, disfunción ventricular o embolia pulmonar de alto riesgo.', 'Función ventricular, valvulopatías, derrame pericárdico, sobrecarga derecha y otros hallazgos estructurales.', 'Puede ser esencial en pacientes inestables y orientar tratamiento inmediato.'],
        ['Pruebas infecciosas dirigidas', 'Ante sospecha de infección respiratoria cuando el resultado tenga impacto en aislamiento, tratamiento o disposición.', 'Identificación de agentes virales o bacterianos según contexto epidemiológico.', 'No deben reemplazar la valoración clínica ni retrasar tratamiento en pacientes graves.'],
        ['Carboxihemoglobina / cooximetría', 'Ante exposición a humo, incendio, combustión o sospecha de monóxido de carbono.', 'Elevación de carboxihemoglobina u otras dishemoglobinas.', 'La pulsioximetría convencional puede ser falsamente tranquilizadora en intoxicación por monóxido de carbono.']
      ]),
      decisionTree: {
        rootNodeId: 'dyspnea-start',
        nodes: [
          { id: 'dyspnea-start', type: 'start', title: 'Paciente con disnea', description: 'Evaluar simultáneamente gravedad, trabajo respiratorio, oxigenación, estabilidad hemodinámica y posibles causas tiempo-dependientes.' },
          { id: 'dyspnea-failure', type: 'question', title: '¿Existe insuficiencia respiratoria grave, agotamiento o inestabilidad?', description: 'Buscar alteración del sensorio, agotamiento, hipoxemia grave, incapacidad para hablar, silencio auscultatorio, shock o deterioro rápido.' },
          { id: 'dyspnea-stabilize', type: 'warning', title: 'Estabilización respiratoria y hemodinámica inmediata', description: 'Oxígeno cuando corresponda, soporte ventilatorio, monitorización y tratamiento simultáneo de la causa.' },
          { id: 'dyspnea-airway', type: 'question', title: '¿Existe obstrucción de vía aérea o anafilaxia?', description: 'Buscar estridor, edema de labios o lengua, urticaria, voz alterada, dificultad para manejar secreciones o exposición compatible.' },
          { id: 'dyspnea-airway-action', type: 'warning', title: 'Tratar vía aérea / anafilaxia de inmediato', description: 'Priorizar manejo de vía aérea y adrenalina intramuscular ante anafilaxia cuando corresponda.' },
          { id: 'dyspnea-unilateral', type: 'question', title: '¿Hay disminución unilateral del murmullo vesicular con sospecha de neumotórax?', description: 'Integrar inicio súbito, dolor torácico, asimetría ventilatoria e inestabilidad.' },
          { id: 'dyspnea-tension', type: 'warning', title: 'Sospecha de neumotórax a tensión', description: 'Si existe inestabilidad y alta sospecha clínica, realizar descompresión urgente sin esperar imagen.' },
          { id: 'dyspnea-edema', type: 'question', title: '¿Predominan congestión pulmonar o signos de insuficiencia cardíaca?', description: 'Buscar ortopnea, crepitantes, líneas B, ingurgitación yugular, edema y antecedentes cardíacos.' },
          { id: 'dyspnea-edema-action', type: 'action', title: 'Tratar posible insuficiencia cardíaca aguda / edema pulmonar', description: 'Soporte ventilatorio y tratamiento hemodinámico dirigido según presión arterial, congestión y causa.' },
          { id: 'dyspnea-bronchospasm', type: 'question', title: '¿Predomina broncoespasmo?', description: 'Buscar sibilancias, espiración prolongada y antecedentes de asma o EPOC.' },
          { id: 'dyspnea-bronchodilator', type: 'action', title: 'Tratamiento broncodilatador y evaluación de gravedad', description: 'Administrar tratamiento inhalado y antiinflamatorio según diagnóstico y valorar respuesta temprana.' },
          { id: 'dyspnea-infection', type: 'question', title: '¿Hay datos de infección respiratoria o sepsis?', description: 'Buscar fiebre, tos, expectoración, infiltrados, hipoxemia y disfunción orgánica.' },
          { id: 'dyspnea-infection-action', type: 'action', title: 'Evaluar y tratar infección respiratoria', description: 'Solicitar estudios dirigidos y administrar antibióticos tempranos cuando exista neumonía bacteriana grave o sepsis.' },
          { id: 'dyspnea-pe', type: 'question', title: '¿Existe sospecha clínica de embolia pulmonar?', description: 'Integrar inicio súbito, dolor pleurítico, síncope, hemoptisis, taquicardia, hipoxemia y factores de riesgo tromboembólico.' },
          { id: 'dyspnea-pe-risk', type: 'action', title: 'Estratificar probabilidad de embolia pulmonar', description: 'Aplicar una estrategia de probabilidad pretest y seleccionar dímero D o imagen según corresponda.' },
          { id: 'dyspnea-cardiac', type: 'question', title: '¿Existe sospecha de causa cardíaca no explicada por congestión?', description: 'Considerar síndrome coronario agudo, arritmias, valvulopatías, miocarditis, pericarditis o taponamiento.' },
          { id: 'dyspnea-cardiac-action', type: 'action', title: 'Evaluación cardiovascular dirigida', description: 'ECG, troponina, POCUS o ecocardiografía según contexto y gravedad.' },
          { id: 'dyspnea-metabolic', type: 'question', title: '¿La taquipnea puede ser compensatoria o extrapulmonar?', description: 'Considerar acidosis metabólica, anemia, intoxicaciones, enfermedad neuromuscular y otras causas sistémicas.' },
          { id: 'dyspnea-metabolic-action', type: 'action', title: 'Buscar causas metabólicas, hematológicas o tóxicas', description: 'Seleccionar gasometría, laboratorio, cooximetría y estudios dirigidos según el contexto.' },
          { id: 'dyspnea-testing', type: 'action', title: 'Integrar estudios complementarios', description: 'Utilizar ECG, radiografía, POCUS, laboratorio y estudios específicos según la hipótesis clínica.' },
          { id: 'dyspnea-serious', type: 'question', title: '¿Se confirmó o continúa siendo altamente probable una causa grave?', description: 'Integrar evolución, respuesta al tratamiento, clínica y estudios.' },
          { id: 'dyspnea-specific', type: 'warning', title: 'Tratamiento específico y evaluación especializada', description: 'Iniciar tratamiento definitivo o dirigido y definir necesidad de intervención, soporte avanzado o internación.' },
          { id: 'dyspnea-reassess', type: 'action', title: 'Reevaluar respuesta al tratamiento', description: 'Reevaluar trabajo respiratorio, frecuencia, saturación, estado mental, auscultación y necesidad de soporte.' },
          { id: 'dyspnea-stable-question', type: 'question', title: '¿El paciente está estable y con respuesta clínica suficiente?', description: 'Debe existir mejoría objetiva, ausencia de signos de agotamiento y una causa manejable de forma segura.' },
          { id: 'dyspnea-critical', type: 'disposition', title: 'Cuidados críticos / intervención urgente', description: 'Indicado ante insuficiencia respiratoria grave, shock, necesidad de ventilación avanzada o enfermedad tiempo-dependiente de alto riesgo.' },
          { id: 'dyspnea-admit', type: 'disposition', title: 'Observación o internación', description: 'Indicado cuando persiste necesidad de oxígeno, tratamiento hospitalario, incertidumbre diagnóstica o riesgo de deterioro.' },
          { id: 'dyspnea-discharge', type: 'disposition', title: 'Alta con tratamiento, seguimiento y pautas de alarma', description: 'Apropiado cuando el paciente está estable, la causa grave ha sido razonablemente excluida y existe respuesta suficiente al tratamiento.' }
        ],
        edges: [
          { id: 'dy-e01', from: 'dyspnea-start', to: 'dyspnea-failure' }, { id: 'dy-e02', from: 'dyspnea-failure', to: 'dyspnea-stabilize', label: 'Sí' }, { id: 'dy-e03', from: 'dyspnea-failure', to: 'dyspnea-airway', label: 'No' },
          { id: 'dy-e04', from: 'dyspnea-stabilize', to: 'dyspnea-airway', label: 'Buscar causa mientras se estabiliza' }, { id: 'dy-e05', from: 'dyspnea-airway', to: 'dyspnea-airway-action', label: 'Sí' }, { id: 'dy-e06', from: 'dyspnea-airway', to: 'dyspnea-unilateral', label: 'No' },
          { id: 'dy-e07', from: 'dyspnea-airway-action', to: 'dyspnea-critical' }, { id: 'dy-e08', from: 'dyspnea-unilateral', to: 'dyspnea-tension', label: 'Sí + inestabilidad' }, { id: 'dy-e09', from: 'dyspnea-unilateral', to: 'dyspnea-edema', label: 'No' },
          { id: 'dy-e10', from: 'dyspnea-tension', to: 'dyspnea-critical' }, { id: 'dy-e11', from: 'dyspnea-edema', to: 'dyspnea-edema-action', label: 'Sí' }, { id: 'dy-e12', from: 'dyspnea-edema', to: 'dyspnea-bronchospasm', label: 'No' },
          { id: 'dy-e13', from: 'dyspnea-edema-action', to: 'dyspnea-testing' }, { id: 'dy-e14', from: 'dyspnea-bronchospasm', to: 'dyspnea-bronchodilator', label: 'Sí' }, { id: 'dy-e15', from: 'dyspnea-bronchospasm', to: 'dyspnea-infection', label: 'No' },
          { id: 'dy-e16', from: 'dyspnea-bronchodilator', to: 'dyspnea-testing' }, { id: 'dy-e17', from: 'dyspnea-infection', to: 'dyspnea-infection-action', label: 'Sí' }, { id: 'dy-e18', from: 'dyspnea-infection', to: 'dyspnea-pe', label: 'No' },
          { id: 'dy-e19', from: 'dyspnea-infection-action', to: 'dyspnea-testing' }, { id: 'dy-e20', from: 'dyspnea-pe', to: 'dyspnea-pe-risk', label: 'Sí' }, { id: 'dy-e21', from: 'dyspnea-pe', to: 'dyspnea-cardiac', label: 'No' },
          { id: 'dy-e22', from: 'dyspnea-pe-risk', to: 'dyspnea-testing' }, { id: 'dy-e23', from: 'dyspnea-cardiac', to: 'dyspnea-cardiac-action', label: 'Sí' }, { id: 'dy-e24', from: 'dyspnea-cardiac', to: 'dyspnea-metabolic', label: 'No' },
          { id: 'dy-e25', from: 'dyspnea-cardiac-action', to: 'dyspnea-testing' }, { id: 'dy-e26', from: 'dyspnea-metabolic', to: 'dyspnea-metabolic-action', label: 'Sí' }, { id: 'dy-e27', from: 'dyspnea-metabolic', to: 'dyspnea-testing', label: 'No / no evidente' },
          { id: 'dy-e28', from: 'dyspnea-metabolic-action', to: 'dyspnea-testing' }, { id: 'dy-e29', from: 'dyspnea-testing', to: 'dyspnea-serious' }, { id: 'dy-e30', from: 'dyspnea-serious', to: 'dyspnea-specific', label: 'Sí' },
          { id: 'dy-e31', from: 'dyspnea-serious', to: 'dyspnea-reassess', label: 'No' }, { id: 'dy-e32', from: 'dyspnea-specific', to: 'dyspnea-critical', label: 'Crítico / requiere intervención inmediata' }, { id: 'dy-e33', from: 'dyspnea-specific', to: 'dyspnea-admit', label: 'Estable pero requiere internación' },
          { id: 'dy-e34', from: 'dyspnea-reassess', to: 'dyspnea-stable-question' }, { id: 'dy-e35', from: 'dyspnea-stable-question', to: 'dyspnea-discharge', label: 'Sí' }, { id: 'dy-e36', from: 'dyspnea-stable-question', to: 'dyspnea-admit', label: 'No' }
        ]
      },
      initialTreatment: richText(
        { kind: 'paragraph', text: 'El tratamiento inicial depende del mecanismo y de la gravedad.' }, { kind: 'heading', text: 'Medidas generales' },
        { kind: 'bullet', items: ['posicionar al paciente según tolerancia', 'monitorización', 'acceso venoso cuando corresponda', 'oxígeno en presencia de hipoxemia o indicación específica', 'tratamiento sintomático y etiológico simultáneo', 'reevaluación frecuente del trabajo respiratorio y estado mental'] },
        { kind: 'heading', text: 'Oxígeno' }, { kind: 'paragraph', text: 'Administrar cuando exista hipoxemia o indicación específica.' }, { kind: 'paragraph', text: 'Evitar utilizar un objetivo único para todos los pacientes. En personas con riesgo de insuficiencia respiratoria hipercápnica crónica, individualizar la meta de saturación.' },
        { kind: 'heading', text: 'Soporte ventilatorio' }, { kind: 'paragraph', text: 'Considerar ventilación no invasiva en escenarios apropiados, especialmente edema agudo de pulmón y determinadas exacerbaciones de EPOC.' }, { kind: 'paragraph', text: 'Considerar intubación y ventilación mecánica ante:' },
        { kind: 'bullet', items: ['deterioro del sensorio', 'agotamiento', 'hipoxemia refractaria', 'incapacidad para proteger vía aérea', 'fracaso del soporte no invasivo', 'paro o deterioro inminente'] },
        { kind: 'heading', text: 'Broncoespasmo' }, { kind: 'paragraph', text: 'Utilizar broncodilatadores inhalados y tratamiento antiinflamatorio según diagnóstico y gravedad.' },
        { kind: 'heading', text: 'Anafilaxia' }, { kind: 'paragraph', text: 'Ante anafilaxia, la adrenalina intramuscular es el tratamiento inicial prioritario, junto con soporte de vía aérea, oxígeno y fluidos según necesidad.' },
        { kind: 'heading', text: 'Edema agudo de pulmón' }, { kind: 'paragraph', text: 'Priorizar soporte ventilatorio, control hemodinámico y tratamiento dirigido según presión arterial, congestión y causa precipitante.' },
        { kind: 'heading', text: 'Neumotórax a tensión' }, { kind: 'paragraph', text: 'Ante alta sospecha clínica con inestabilidad, realizar descompresión urgente sin esperar confirmación radiológica.' },
        { kind: 'heading', text: 'Infección respiratoria grave' }, { kind: 'paragraph', text: 'Administrar antibióticos apropiados tempranamente cuando exista neumonía bacteriana grave o sepsis.' }
      ),
      reassessment: richText(
        { kind: 'paragraph', text: 'La reevaluación debe ser frecuente y dirigida a detectar mejoría, falta de respuesta o agotamiento.' }, { kind: 'paragraph', text: 'Reevaluar:' },
        { kind: 'bullet', items: ['frecuencia respiratoria', 'trabajo respiratorio', 'capacidad para hablar', 'saturación', 'estado mental', 'auscultación', 'presión arterial', 'frecuencia cardíaca', 'respuesta a oxígeno', 'respuesta a broncodilatadores', 'respuesta a ventilación no invasiva', 'necesidad creciente de soporte'] },
        { kind: 'paragraph', text: 'Un paciente inicialmente taquipneico puede deteriorarse y desarrollar una frecuencia respiratoria aparentemente “normal” por fatiga. La disminución del esfuerzo respiratorio no siempre representa mejoría.' }
      ),
      disposition: {
        discharge: richText({ kind: 'paragraph', text: 'Considerar alta cuando:' }, { kind: 'bullet', items: ['paciente hemodinámicamente estable', 'sin signos de insuficiencia respiratoria', 'oxigenación adecuada para su condición basal', 'causa grave razonablemente excluida', 'buena respuesta al tratamiento', 'tolera actividad acorde al contexto', 'puede continuar tratamiento ambulatorio', 'cuenta con seguimiento', 'comprende pautas de alarma'] }),
        admission: richText({ kind: 'paragraph', text: 'Considerar internación ante:' }, { kind: 'bullet', items: ['persistencia de disnea', 'necesidad de oxígeno', 'exacerbación moderada o grave', 'neumonía que requiere tratamiento hospitalario', 'insuficiencia cardíaca', 'embolia pulmonar que no cumple criterios de manejo ambulatorio', 'comorbilidad relevante', 'incertidumbre diagnóstica', 'respuesta insuficiente al tratamiento inicial', 'imposibilidad de seguimiento seguro'] }),
        criticalCare: richText({ kind: 'paragraph', text: 'Considerar ante:' }, { kind: 'bullet', items: ['insuficiencia respiratoria grave', 'necesidad de ventilación invasiva', 'ventilación no invasiva con alta vigilancia', 'shock', 'embolia pulmonar de alto riesgo', 'asma casi fatal', 'edema pulmonar grave', 'neumonía con falla orgánica', 'neumotórax a tensión', 'taponamiento', 'deterioro progresivo'] }),
        referral: richText({ kind: 'paragraph', text: 'Según etiología considerar:' }, { kind: 'bullet', items: ['Neumonología.', 'Cardiología.', 'Terapia intensiva.', 'Cirugía torácica.', 'Hemodinamia.', 'Toxicología.', 'Alergia/inmunología.', 'Centro de mayor complejidad.'] })
      },
      warningsAndInstructions: richText({ kind: 'paragraph', text: 'Indicar nueva evaluación urgente ante:' }, { kind: 'bullet', items: ['aumento de la dificultad respiratoria', 'incapacidad para hablar o caminar por falta de aire', 'dolor torácico', 'síncope', 'confusión o somnolencia', 'cianosis', 'hemoptisis', 'fiebre persistente con deterioro', 'edema progresivo', 'necesidad creciente de medicación de rescate', 'mala respuesta al tratamiento indicado', 'aparición de estridor', 'empeoramiento general'] }),
      commonErrors: richText({ kind: 'bullet', items: ['Interpretar toda disnea con sibilancias como asma.', 'Interpretar toda disnea con crepitantes como insuficiencia cardíaca.', 'Confiar exclusivamente en la saturación de oxígeno.', 'No reconocer agotamiento respiratorio cuando disminuye la frecuencia respiratoria.', 'No considerar embolia pulmonar en pacientes con radiografía normal.', 'Solicitar dímero D en pacientes de alta probabilidad clínica sin una estrategia apropiada.', 'No considerar síndrome coronario agudo cuando la disnea es el síntoma predominante.', 'Retrasar tratamiento de neumotórax a tensión para obtener imágenes.', 'Retrasar adrenalina en anafilaxia.', 'Usar oxígeno indiscriminadamente sin definir objetivo clínico.', 'No evaluar exposición a monóxido de carbono.', 'Confundir hiperventilación secundaria a acidosis metabólica con ansiedad.', 'No reevaluar respuesta al tratamiento.', 'No considerar anemia o causas extrapulmonares.', 'Atribuir disnea a ansiedad antes de excluir razonablemente causas orgánicas relevantes.'] }),
      clinicalPearls: richText({ kind: 'bullet', items: ['La disnea es un síntoma; el objetivo inicial es identificar el mecanismo y la gravedad antes que etiquetar un diagnóstico.', 'Trabajo respiratorio y estado mental pueden ser más informativos que una saturación aislada.', 'Una frecuencia respiratoria que disminuye en un paciente fatigado puede indicar deterioro y no mejoría.', 'La ausencia de hipoxemia no descarta enfermedad grave.', 'Una radiografía normal no excluye embolia pulmonar.', 'Sibilancias también pueden aparecer en insuficiencia cardíaca.', 'Crepitantes pueden estar ausentes en edema pulmonar temprano.', 'La taquipnea puede ser compensación de una acidosis metabólica.', 'No toda disnea es pulmonar.', 'POCUS puede ser especialmente útil cuando se utiliza para responder preguntas clínicas concretas.'] }),
      relatedContent: []
    }
  };
  const validation = validateDecisionTree(approach.content.decisionTree);
  if (validation.errors.length > 0) throw new Error(`El fixture de Disnea contiene un árbol inválido: ${validation.errors.map((issue) => issue.message).join(' ')}`);
  return approach;
}
