import type { TipTapDocument } from '../../types/topic';
import type { ClinicalApproach, ClinicalApproachContent, ComplementaryStudy, DecisionTree, DifferentialDiagnosisItem, ReasoningItem } from './clinicalApproachTypes';
import { validateDecisionTree } from './decisionTreeValidation';

type TextBlock = { kind: 'paragraph' | 'heading'; text: string } | { kind: 'bullet'; items: string[] };
type PolytraumaApproachBaseContent = Pick<ClinicalApproachContent,
  'version' | 'presentation' | 'initialAssessment' | 'lifeThreats' | 'anamnesis' | 'physicalExam'
  | 'differentialDiagnosis' | 'complementaryStudies' | 'initialTreatment' | 'reassessment' | 'disposition'
  | 'warningsAndInstructions' | 'commonErrors' | 'clinicalPearls'
>;

const textNode = (text: string) => ({ type: 'text', text });
const richText = (...blocks: TextBlock[]): TipTapDocument => ({
  type: 'doc',
  content: blocks.map((block) => block.kind === 'bullet'
    ? { type: 'bulletList', content: block.items.map((item) => ({ type: 'listItem', content: [{ type: 'paragraph', content: [textNode(item)] }] })) }
    : { type: block.kind, ...(block.kind === 'heading' ? { attrs: { level: 3 } } : {}), content: [textNode(block.text)] })
});
const paragraph = (text: string): TipTapDocument => richText({ kind: 'paragraph', text });
const stableId = (group: number, index: number) => `9017${group.toString().padStart(4, '0')}-0000-4000-8000-${index.toString().padStart(12, '0')}`;
const reasoning = (group: number, entries: Array<[string, string, string]>): ReasoningItem[] => entries.map(([title, content, whyItMatters], index) => ({
  id: stableId(group, index + 1), title, content: paragraph(content), whyItMatters: paragraph(whyItMatters)
}));
const differentials = (group: number, entries: Array<[string, string]>): DifferentialDiagnosisItem[] => entries.map(([title, explanation], index) => ({
  id: stableId(group, index + 1), title, explanation: paragraph(explanation)
}));
const studies = (entries: Array<[string, string, string, string]>): ComplementaryStudy[] => entries.map(([name, whenToOrder, targetFinding, interpretation], index) => ({
  id: stableId(6, index + 1), name, whenToOrder: paragraph(whenToOrder), targetFinding: paragraph(targetFinding), interpretation: paragraph(interpretation)
}));

export const POLYTRAUMA_APPROACH_TITLE = 'Politrauma';
export const POLYTRAUMA_APPROACH_DESCRIPTION = 'Abordaje inicial del paciente con trauma potencialmente grave o múltiples lesiones, orientado a la identificación y tratamiento inmediato de amenazas vitales mediante una secuencia XABCDE, control precoz de hemorragia, protección de la vía aérea y columna cervical, reconocimiento de lesiones torácicas y abdominales tiempo-dependientes, evaluación neurológica, prevención de hipotermia y reevaluación continua.';

export function createPolytraumaApproachBaseContent(): PolytraumaApproachBaseContent {
  return {
    version: 1,
    presentation: richText(
      { kind: 'paragraph', text: 'El politrauma debe abordarse como una enfermedad dinámica y tiempo-dependiente. El objetivo inicial no es definir todas las lesiones, sino identificar y tratar primero aquellas que amenazan la vida de forma inmediata.' },
      { kind: 'paragraph', text: 'La evaluación primaria debe realizarse con un enfoque XABCDE:' },
      { kind: 'heading', text: 'X — Hemorragia exanguinante' },
      { kind: 'paragraph', text: 'Control inmediato de hemorragia externa catastrófica antes del resto de la evaluación.' },
      { kind: 'heading', text: 'A — Airway / vía aérea con protección cervical' },
      { kind: 'paragraph', text: 'Asegurar permeabilidad y protección de la vía aérea manteniendo precauciones cervicales cuando el mecanismo lo indique.' },
      { kind: 'heading', text: 'B — Breathing / ventilación' },
      { kind: 'paragraph', text: 'Identificar lesiones torácicas que comprometen ventilación u oxigenación.' },
      { kind: 'heading', text: 'C — Circulation / circulación' },
      { kind: 'paragraph', text: 'Buscar y tratar shock, hemorragia externa y fuentes ocultas de sangrado.' },
      { kind: 'heading', text: 'D — Disability / neurológico' },
      { kind: 'paragraph', text: 'Evaluar nivel de conciencia, pupilas, focalidad, glucemia cuando corresponda y signos de lesión neurológica.' },
      { kind: 'heading', text: 'E — Exposure / exposición' },
      { kind: 'paragraph', text: 'Exponer al paciente para examinarlo completamente y prevenir activamente la hipotermia.' },
      { kind: 'paragraph', text: 'El tratamiento de una amenaza vital no debe retrasarse para completar la secuencia.' },
      { kind: 'paragraph', text: 'La evaluación inicial debe responder rápidamente:' },
      { kind: 'bullet', items: ['¿Existe hemorragia catastrófica?', '¿La vía aérea está amenazada?', '¿Existe lesión cervical potencial?', '¿Hay neumotórax a tensión?', '¿Hay hemotórax masivo?', '¿Hay compromiso ventilatorio?', '¿Existe shock?', '¿Dónde puede estar sangrando?', '¿Hay taponamiento?', '¿Existe lesión abdominal o pélvica grave?', '¿Hay traumatismo craneoencefálico?', '¿Existe lesión medular?', '¿Hay fracturas abiertas o lesiones vasculares?', '¿Se requiere cirugía, hemostasia, toracostomía o traslado inmediato?', '¿La respuesta a las intervenciones confirma la hipótesis?'] },
      { kind: 'paragraph', text: 'Un paciente con trauma puede presentar múltiples causas de deterioro simultáneas. El shock puede ser hemorrágico, obstructivo, neurogénico, cardiogénico o mixto.' },
      { kind: 'paragraph', text: 'No asumir que la ausencia de hipotensión excluye una hemorragia significativa.' }
    ),
    initialAssessment: richText(
      { kind: 'heading', text: 'X — Hemorragia exanguinante' },
      { kind: 'paragraph', text: 'Antes de evaluar formalmente la vía aérea, identificar sangrado externo catastrófico.' },
      { kind: 'paragraph', text: 'Buscar:' },
      { kind: 'bullet', items: ['amputaciones', 'heridas penetrantes', 'sangrado pulsátil', 'heridas extensas', 'hemorragia de extremidades', 'sangrado de unión inguinal/axilar/cuello', 'hemorragia obstétrica traumática si corresponde'] },
      { kind: 'paragraph', text: 'Medidas inmediatas según sitio y recursos:' },
      { kind: 'bullet', items: ['compresión directa', 'vendaje compresivo', 'torniquete en extremidad cuando esté indicado', 'empaquetamiento de heridas profundas/junctional', 'agentes hemostáticos según disponibilidad/protocolo'] },
      { kind: 'paragraph', text: 'Registrar hora de colocación del torniquete.' },
      { kind: 'paragraph', text: 'No retirar un torniquete efectivo durante la fase inicial fuera de un entorno preparado para control definitivo del sangrado.' },
      { kind: 'heading', text: 'A — Vía aérea + protección cervical' },
      { kind: 'paragraph', text: 'Evaluar:' },
      { kind: 'bullet', items: ['capacidad para hablar', 'sonidos anormales', 'ronquido', 'estridor', 'gorgoteo', 'sangre/vómitos/secreciones', 'trauma facial', 'quemadura/inhalación', 'hematoma cervical', 'enfisema subcutáneo', 'nivel de conciencia'] },
      { kind: 'paragraph', text: 'Si el paciente habla con claridad, la vía aérea está permeable en ese momento, pero puede deteriorarse.' },
      { kind: 'paragraph', text: 'Mantener precaución cervical cuando exista:' },
      { kind: 'bullet', items: ['mecanismo significativo', 'dolor cervical', 'alteración neurológica', 'alteración del sensorio', 'lesión distractora', 'imposibilidad de evaluar clínicamente'] },
      { kind: 'paragraph', text: 'No retrasar una vía aérea necesaria por intentar completar estudios cervicales.' },
      { kind: 'paragraph', text: 'La inmovilización debe ser razonada y no interferir con la reanimación.' },
      { kind: 'paragraph', text: 'Considerar vía aérea definitiva ante:' },
      { kind: 'bullet', items: ['incapacidad para proteger la vía aérea', 'apnea', 'hipoxemia refractaria', 'ventilación insuficiente', 'trauma facial grave', 'deterioro progresivo', 'Glasgow muy reducido con pérdida de reflejos protectores', 'necesidad anticipada de traslado/procedimiento con alto riesgo de deterioro'] },
      { kind: 'paragraph', text: 'La intubación del paciente traumatizado y en shock es un procedimiento de alto riesgo hemodinámico.' },
      { kind: 'paragraph', text: 'Preparar:' },
      { kind: 'bullet', items: ['preoxigenación', 'succión', 'plan de vía aérea difícil', 'respaldo quirúrgico si corresponde', 'estabilización hemodinámica', 'vasopresores disponibles', 'estrategia de rescate'] },
      { kind: 'heading', text: 'B — Respiración / ventilación' },
      { kind: 'paragraph', text: 'Evaluar:' },
      { kind: 'bullet', items: ['frecuencia respiratoria', 'SpO2', 'simetría torácica', 'expansión', 'uso de músculos accesorios', 'heridas abiertas', 'enfisema subcutáneo', 'desviación traqueal si existe', 'auscultación', 'percusión cuando aporte', 'signos de fatiga'] },
      { kind: 'paragraph', text: 'Lesiones torácicas inmediatamente amenazantes:' },
      { kind: 'heading', text: '1. Neumotórax a tensión' },
      { kind: 'paragraph', text: 'Deterioro respiratorio/hemodinámico con hallazgos compatibles requiere descompresión inmediata. No esperar radiografía si la sospecha clínica es alta.' },
      { kind: 'heading', text: '2. Neumotórax abierto' },
      { kind: 'paragraph', text: 'Herida torácica comunicante con compromiso ventilatorio. Requiere manejo inmediato de la herida y drenaje según protocolo.' },
      { kind: 'heading', text: '3. Hemotórax masivo' },
      { kind: 'paragraph', text: 'Sangrado pleural significativo con shock y disminución del murmullo. Requiere drenaje torácico, reanimación y evaluación quirúrgica.' },
      { kind: 'heading', text: '4. Tórax inestable con contusión pulmonar' },
      { kind: 'paragraph', text: 'Puede causar insuficiencia respiratoria progresiva. Priorizar analgesia, oxigenación y soporte ventilatorio según necesidad.' },
      { kind: 'heading', text: '5. Taponamiento cardíaco' },
      { kind: 'paragraph', text: 'Puede manifestarse como shock obstructivo. POCUS puede acelerar reconocimiento en el contexto apropiado.' },
      { kind: 'heading', text: 'C — Circulación / hemorragia' },
      { kind: 'paragraph', text: 'Evaluar:' },
      { kind: 'bullet', items: ['pulso', 'frecuencia y ritmo', 'PA/PAM', 'perfusión periférica', 'relleno capilar', 'temperatura', 'estado mental', 'diuresis', 'hemorragia externa', 'abdomen', 'pelvis', 'tórax', 'huesos largos', 'retroperitoneo como fuente potencial'] },
      { kind: 'paragraph', text: 'Fuentes mayores de hemorragia oculta:' },
      { kind: 'bullet', items: ['tórax', 'abdomen', 'pelvis/retroperitoneo', 'huesos largos'] },
      { kind: 'paragraph', text: 'Principios:' },
      { kind: 'bullet', items: ['controlar sangrado', 'obtener accesos vasculares de gran calibre o alternativa apropiada', 'obtener muestras sin retrasar reanimación', 'activar protocolo de hemorragia masiva cuando corresponda', 'priorizar hemoderivados sobre grandes volúmenes de cristaloides en hemorragia grave', 'prevenir hipotermia', 'vigilar calcio', 'corregir coagulopatía de forma dirigida', 'coordinar control definitivo del sangrado'] },
      { kind: 'paragraph', text: 'En trauma hemorrágico sin TCE grave, puede utilizarse una estrategia de presión permisiva según protocolos y contexto hasta hemostasia.' },
      { kind: 'paragraph', text: 'En traumatismo craneoencefálico grave, evitar hipotensión y preservar perfusión cerebral.' },
      { kind: 'heading', text: 'D — Neurológico' },
      { kind: 'paragraph', text: 'Evaluar:' },
      { kind: 'bullet', items: ['Glasgow', 'pupilas', 'simetría', 'respuesta motora', 'focalidad', 'lateralización', 'convulsiones', 'nivel de conciencia', 'glucemia cuando corresponda'] },
      { kind: 'paragraph', text: 'Un descenso del Glasgow puede deberse a:' },
      { kind: 'bullet', items: ['TCE', 'hipoxia', 'shock', 'intoxicación', 'hipoglucemia', 'convulsiones', 'otras causas'] },
      { kind: 'paragraph', text: 'No atribuir automáticamente la alteración mental al alcohol o drogas sin excluir lesión cerebral e hipoperfusión.' },
      { kind: 'paragraph', text: 'Buscar signos de herniación:' },
      { kind: 'bullet', items: ['deterioro rápido del sensorio', 'anisocoria', 'posturas anormales', 'hipertensión con bradicardia en fases tardías', 'alteraciones respiratorias'] },
      { kind: 'paragraph', text: 'Evitar:' },
      { kind: 'bullet', items: ['hipoxia', 'hipotensión', 'hipercapnia grave', 'hipocapnia profiláctica innecesaria'] },
      { kind: 'heading', text: 'E — Exposición y control ambiental' },
      { kind: 'paragraph', text: 'Exponer completamente al paciente para detectar:' },
      { kind: 'bullet', items: ['heridas', 'sangrado', 'deformidades', 'lesiones dorsales', 'quemaduras', 'lesiones perineales', 'lesiones de extremidades', 'fracturas abiertas', 'signos de aplastamiento'] },
      { kind: 'paragraph', text: 'Realizar log-roll o movilización coordinada cuando sea apropiado y seguro.' },
      { kind: 'paragraph', text: 'Prevenir activamente hipotermia:' },
      { kind: 'bullet', items: ['mantas', 'ambiente cálido', 'fluidos/hemoderivados calentados cuando corresponda', 'minimizar exposición innecesaria'] },
      { kind: 'paragraph', text: 'La hipotermia empeora coagulopatía y pronóstico.' },
      { kind: 'heading', text: 'Adjuntos a la evaluación primaria' },
      { kind: 'paragraph', text: 'Sin retrasar intervenciones esenciales, considerar:' },
      { kind: 'bullet', items: ['monitor ECG', 'SpO2', 'presión arterial repetida/invasiva según gravedad', 'temperatura', 'capnografía si vía aérea avanzada', 'gasometría/lactato', 'eFAST', 'radiografía portátil según contexto', 'laboratorio', 'banco de sangre', 'sonda vesical cuando no esté contraindicada', 'sonda gástrica según indicación y precauciones'] },
      { kind: 'heading', text: 'Reevaluación primaria continua' },
      { kind: 'paragraph', text: 'Después de cada intervención repetir XABCDE.' },
      { kind: 'paragraph', text: 'Preguntar:' },
      { kind: 'bullet', items: ['¿sigue sangrando?', '¿la vía aérea continúa segura?', '¿la ventilación mejoró?', '¿apareció un neumotórax?', '¿la perfusión mejoró?', '¿hay nueva hipotensión?', '¿el Glasgow cambió?', '¿está desarrollando hipotermia?', '¿apareció una lesión antes oculta?'] }
    ),
    lifeThreats: richText(
      { kind: 'paragraph', text: 'Priorizar reconocimiento y tratamiento inmediato de:' },
      { kind: 'bullet', items: ['hemorragia externa exanguinante', 'obstrucción o pérdida de vía aérea', 'trauma facial grave con vía aérea amenazada', 'neumotórax a tensión', 'neumotórax abierto', 'hemotórax masivo', 'taponamiento cardíaco', 'hemorragia intratorácica', 'hemorragia intraabdominal', 'fractura pélvica con inestabilidad/hemorragia', 'hemorragia retroperitoneal', 'lesión vascular mayor', 'amputación traumática', 'shock hemorrágico', 'TCE grave con herniación', 'hematoma epidural/subdural con deterioro', 'lesión medular con compromiso neurológico/hemodinámico', 'fractura abierta con lesión vascular', 'síndrome compartimental', 'lesión aórtica traumática', 'ruptura diafragmática con compromiso', 'lesión de víscera hueca/peritonitis', 'embarazo con trauma y hemorragia', 'quemaduras extensas o lesión inhalatoria', 'hipotermia grave asociada a trauma'] },
      { kind: 'heading', text: 'Hemorragia exanguinante' },
      { kind: 'paragraph', text: 'El control de sangrado puede preceder a la vía aérea si la hemorragia externa es inmediatamente letal.' },
      { kind: 'heading', text: 'Neumotórax a tensión' },
      { kind: 'paragraph', text: 'No retrasar descompresión por estudios de imagen en paciente inestable con alta sospecha.' },
      { kind: 'heading', text: 'Hemotórax masivo' },
      { kind: 'paragraph', text: 'Drenaje, reanimación y evaluación quirúrgica deben realizarse rápidamente.' },
      { kind: 'heading', text: 'Taponamiento cardíaco' },
      { kind: 'paragraph', text: 'El tratamiento definitivo es la descompresión/drenaje; POCUS puede facilitar el diagnóstico.' },
      { kind: 'heading', text: 'Fractura pélvica hemorrágica' },
      { kind: 'paragraph', text: 'Considerar estabilización pélvica precoz, reanimación hemostática y control definitivo mediante cirugía/intervencionismo según recursos.' },
      { kind: 'heading', text: 'TCE grave' },
      { kind: 'paragraph', text: 'Evitar lesión secundaria por hipoxia e hipotensión.' },
      { kind: 'heading', text: 'Lesión vascular de extremidad' },
      { kind: 'paragraph', text: 'Buscar hemorragia, ausencia de pulso, isquemia, hematoma expansivo y soplo/frémito. Los signos duros requieren evaluación vascular urgente.' }
    ),
    anamnesis: reasoning(1, [
      ['Mecanismo del trauma', 'Definir colisión, caída, atropello, aplastamiento, penetrante, arma, explosión u otro mecanismo.', 'El mecanismo orienta energía transferida y patrones de lesión ocultos.'],
      ['Hora del evento', 'Registrar momento del trauma y tiempos hasta atención.', 'Permite interpretar evolución, hemorragia, hipotermia y ventanas terapéuticas.'],
      ['Velocidad/energía del impacto', 'Preguntar por velocidad aproximada, altura de caída, deformación vehicular y otros datos.', 'Mayor energía aumenta riesgo de lesiones internas múltiples.'],
      ['Uso de cinturón/casco/airbag', 'Preguntar por sistemas de protección.', 'Modifica patrón esperado de lesiones.'],
      ['Eyección o atrapamiento', 'Preguntar si hubo eyección, vuelco o atrapamiento prolongado.', 'Se asocia a trauma de alta energía.'],
      ['Pérdida de conciencia', 'Preguntar por amnesia, síncope o pérdida de conciencia.', 'Sugiere TCE y obliga a diferenciar causa previa al trauma.'],
      ['Dolor cervical o neurológico', 'Preguntar por dolor cervical, parestesias, debilidad o pérdida sensitiva.', 'Orienta a lesión cervical/medular.'],
      ['Disnea o dolor torácico', 'Preguntar por disnea, dolor pleurítico y dificultad respiratoria.', 'Puede indicar neumotórax, hemotórax, contusión pulmonar o lesión cardíaca.'],
      ['Dolor abdominal', 'Preguntar por localización y progresión.', 'Puede orientar a lesión visceral o hemorragia.'],
      ['Dolor pélvico', 'Preguntar por dolor de pelvis, cadera o periné.', 'Puede sugerir fractura pélvica y hemorragia asociada.'],
      ['Sangrado visible', 'Preguntar por hemorragia externa, hematemesis, hematuria, sangrado vaginal u otros.', 'Identifica fuentes directas de pérdida sanguínea.'],
      ['Embarazo posible', 'Preguntar por embarazo, edad gestacional y fecha de última menstruación si corresponde.', 'Modifica prioridades, diagnóstico, posicionamiento, radiología y necesidad de evaluación obstétrica.'],
      ['Medicación anticoagulante/antiagregante', 'Registrar anticoagulantes, antiagregantes y última dosis.', 'Aumentan riesgo de hemorragia y condicionan reversión.'],
      ['Alergias', 'Registrar alergias medicamentosas conocidas.', 'Es parte de AMPLE y condiciona tratamiento.'],
      ['Medicación habitual', 'Preguntar por fármacos cardiovasculares, insulina, corticoides y otros relevantes.', 'Puede modificar respuesta fisiológica y decisiones terapéuticas.'],
      ['Enfermedades previas', 'Preguntar por cardiopatía, enfermedad pulmonar, renal, hepática, trastornos de coagulación y epilepsia.', 'Modifican reserva fisiológica y estrategia de reanimación.'],
      ['Última ingesta', 'Registrar última comida/bebida.', 'Aporta información para anestesia/procedimientos urgentes.'],
      ['Eventos previos al trauma', 'Preguntar por dolor torácico, síncope, convulsión, déficit neurológico o intoxicación antes del evento.', 'El trauma puede ser consecuencia de una emergencia médica primaria.'],
      ['Alcohol y drogas', 'Preguntar por consumo reciente cuando sea posible.', 'Puede alterar sensorio, pero nunca debe utilizarse para explicar deterioro sin excluir lesión grave.'],
      ['Tratamientos prehospitalarios', 'Registrar torniquetes, vía aérea, fluidos, transfusión, medicación, inmovilización y respuesta.', 'La evolución frente a las intervenciones aporta información y evita duplicar o revertir medidas útiles.']
    ]),
    physicalExam: reasoning(2, [
      ['Hemorragia externa', 'Buscar activamente sangrado catastrófico, heridas penetrantes, amputaciones y sangrado de unión.', 'El control inmediato puede ser la intervención más urgente.'],
      ['Vía aérea', 'Evaluar voz, sonidos, secreciones, sangre, trauma facial y capacidad para protegerla.', 'La obstrucción puede evolucionar rápidamente.'],
      ['Columna cervical', 'Evaluar dolor, deformidad, déficit neurológico y mecanismo.', 'Permite decidir precauciones cervicales sin retrasar reanimación.'],
      ['Tórax', 'Inspeccionar, palpar y auscultar buscando asimetría, heridas, enfisema, dolor y ventilación.', 'Identifica lesiones torácicas letales.'],
      ['Perfusión', 'Evaluar pulsos, relleno capilar, temperatura, color y moteado.', 'Puede revelar shock antes de hipotensión.'],
      ['Signos vitales', 'Registrar PA/PAM, FC, FR, SpO2 y temperatura con tendencias.', 'El deterioro dinámico exige mediciones repetidas.'],
      ['Abdomen', 'Buscar distensión, dolor, defensa, heridas y signos peritoneales.', 'La lesión abdominal puede producir hemorragia oculta o perforación.'],
      ['Pelvis', 'Evaluar dolor, deformidad y mecanismo, evitando maniobras repetidas de compresión.', 'La fractura pélvica puede causar hemorragia masiva.'],
      ['Periné y genitales', 'Buscar hematomas, sangre uretral, lesiones y sangrado.', 'Puede indicar lesión pélvica, uretral o gineco-obstétrica.'],
      ['Neurológico', 'Glasgow, pupilas, motor, sensibilidad y focalidad.', 'Detecta TCE y lesión medular y permite seguir deterioro.'],
      ['Cabeza y cara', 'Buscar heridas, deformidad, signos de fractura de base de cráneo, trauma ocular y maxilofacial.', 'Puede amenazar vía aérea, visión o encéfalo.'],
      ['Dorso', 'Examinar durante movilización coordinada cuando sea seguro.', 'Lesiones dorsales pueden pasar inadvertidas.'],
      ['Extremidades', 'Buscar deformidad, heridas, fracturas abiertas, pulsos y perfusión distal.', 'Identifica hemorragia, lesión vascular y riesgo de síndrome compartimental.'],
      ['Pulsos distales y estado vascular', 'Comparar pulsos, temperatura, color y relleno distal.', 'Ausencia de pulso o isquemia tras trauma requiere evaluación vascular urgente.'],
      ['Temperatura e hipotermia', 'Medir temperatura y buscar exposición prolongada.', 'La hipotermia empeora coagulopatía y mortalidad.'],
      ['eFAST/POCUS contextual', 'Cuando exista entrenamiento y disponibilidad, evaluar líquido libre pericárdico, intraperitoneal y pleural, además de neumotórax según protocolo.', 'Puede acelerar decisiones en paciente inestable sin retrasar tratamiento de lesiones clínicamente evidentes.']
    ]),
    differentialDiagnosis: {
      lifeThreatening: differentials(3, [
        ['Hemorragia externa exanguinante', 'Sangrado masivo de extremidades, heridas penetrantes, amputaciones o zonas de unión. El control inmediato puede preceder a la evaluación formal de la vía aérea.'],
        ['Shock hemorrágico por sangrado oculto', 'Tórax, abdomen, pelvis/retroperitoneo y huesos largos son fuentes principales. La ausencia de sangrado externo o una hemoglobina inicial normal no lo excluyen.'],
        ['Obstrucción o pérdida inminente de vía aérea', 'Sangre, vómitos, trauma facial, hematoma cervical, edema o deterioro neurológico pueden comprometer rápidamente la vía aérea.'],
        ['Neumotórax a tensión', 'Produce insuficiencia respiratoria y shock obstructivo. En paciente inestable con alta sospecha clínica, descomprimir sin esperar imagen.'],
        ['Hemotórax masivo', 'Acumulación sanguínea pleural significativa con compromiso respiratorio/hemodinámico. Requiere drenaje, reanimación y evaluación quirúrgica.'],
        ['Neumotórax abierto', 'Herida torácica comunicante que altera la mecánica ventilatoria. Requiere tratamiento inmediato de la herida y drenaje según protocolo.'],
        ['Taponamiento cardíaco traumático', 'Especialmente tras trauma penetrante. POCUS puede acelerar el diagnóstico; el compromiso hemodinámico requiere descompresión/drenaje urgente.'],
        ['Hemorragia intraabdominal grave', 'Lesiones hepáticas, esplénicas, vasculares o mesentéricas pueden causar shock. En inestabilidad, priorizar hemostasia sobre estudios demorados.'],
        ['Fractura pélvica hemorrágica', 'Puede causar hemorragia retroperitoneal masiva. Requiere estabilización pélvica, reanimación hemostática y control definitivo mediante cirugía/intervencionismo según recursos.'],
        ['Traumatismo craneoencefálico grave', 'La lesión cerebral primaria puede agravarse por hipoxia e hipotensión. Priorizar oxigenación y perfusión adecuadas.'],
        ['Herniación cerebral', 'Deterioro neurológico rápido, anisocoria y posturas anormales requieren manejo neurocrítico urgente y neurocirugía.'],
        ['Lesión vascular mayor', 'Ausencia de pulso, isquemia, hemorragia pulsátil, hematoma expansivo o soplo/frémito son signos de alarma para lesión arterial significativa.'],
        ['Lesión aórtica traumática', 'Trauma de alta energía puede producir lesión de aorta torácica o abdominal, con riesgo de ruptura y muerte.'],
        ['Lesión medular con compromiso respiratorio o hemodinámico', 'Lesión cervical alta puede causar insuficiencia respiratoria y shock neurogénico; siempre excluir hemorragia concomitante.']
      ]),
      common: differentials(4, [
        ['Contusión pulmonar', 'Puede causar hipoxemia progresiva, especialmente durante las primeras horas.'],
        ['Fracturas costales múltiples', 'Dolor, hipoventilación y riesgo de complicaciones pulmonares; en mayores pueden tener elevada morbimortalidad.'],
        ['Tórax inestable', 'Segmento costal móvil asociado frecuentemente a contusión pulmonar y deterioro ventilatorio.'],
        ['Lesión hepática', 'Frecuente en trauma abdominal cerrado y potencial fuente de hemorragia significativa.'],
        ['Lesión esplénica', 'Fuente habitual de hemoperitoneo tras trauma abdominal cerrado.'],
        ['Fractura de pelvis', 'Puede acompañarse de hemorragia, lesión urológica y daño de partes blandas.'],
        ['Fracturas de huesos largos', 'Pueden producir pérdida sanguínea importante, dolor y síndrome compartimental.'],
        ['Fracturas abiertas', 'Riesgo de hemorragia, contaminación, infección y lesión neurovascular.'],
        ['Conmoción/TCE leve-moderado', 'Puede coexistir con lesiones intracraneales estructurales, especialmente con factores de riesgo.'],
        ['Lesiones de partes blandas', 'Laceraciones, abrasiones, hematomas y heridas requieren evaluación después de controlar amenazas vitales.']
      ]),
      contextual: differentials(5, [
        ['Lesión diafragmática', 'Puede pasar inadvertida y causar herniación visceral o compromiso respiratorio.'],
        ['Contusión miocárdica', 'Trauma torácico cerrado puede producir arritmias o disfunción ventricular.'],
        ['Rotura traumática de víscera hueca', 'Dolor o peritonitis pueden ser tardíos; la TC y reevaluación seriada son importantes.'],
        ['Lesión pancreática', 'Puede ser inicialmente poco sintomática y diagnosticarse tardíamente.'],
        ['Lesión renal', 'Hematuria, dolor lumbar o mecanismo de alta energía pueden orientar.'],
        ['Lesión vesical', 'Asociada a fractura pélvica y hematuria.'],
        ['Lesión uretral', 'Sangre en meato, hematoma perineal o incapacidad para orinar; evitar sondaje uretral ciego si se sospecha.'],
        ['Lesión de columna toracolumbar', 'Puede coexistir con déficit neurológico o ser inicialmente oculta.'],
        ['Síndrome compartimental', 'Dolor desproporcionado, dolor con estiramiento pasivo y evolución progresiva requieren diagnóstico precoz.'],
        ['Lesión vascular de extremidad sin signos duros', 'Puede requerir índice tobillo-brazo, Doppler o angio-TC según contexto.'],
        ['Lesión ocular traumática', 'Trauma penetrante, disminución visual, pupila irregular o prolapso requieren oftalmología urgente.'],
        ['Trauma maxilofacial complejo', 'Puede comprometer vía aérea, visión y control hemorrágico.'],
        ['Quemaduras asociadas', 'Valorar extensión, profundidad, lesión inhalatoria y necesidad de reanimación específica.'],
        ['Lesión inhalatoria', 'Sospechar ante incendio en espacio cerrado, hollín, quemaduras faciales, disfonía o estridor.'],
        ['Rabdomiólisis por aplastamiento', 'Puede causar hiperpotasemia, lesión renal y arritmias.'],
        ['Embolia grasa', 'Puede aparecer tras fracturas de huesos largos con deterioro respiratorio y neurológico.'],
        ['Trauma en embarazo', 'Requiere estabilizar primero a la madre y luego valoración obstétrica/fetal según edad gestacional.'],
        ['Trauma en anticoagulado', 'Aumenta riesgo de hemorragia intracraneal y otras hemorragias, con umbral más bajo para estudios y reversión específica cuando corresponda.']
      ])
    },
    complementaryStudies: studies([
      ['Hemograma', 'Trauma moderado/grave, sospecha de hemorragia o necesidad de internación.', 'Hemoglobina, hematocrito, plaquetas y leucocitos.', 'Una hemoglobina inicial normal no excluye hemorragia aguda; utilizar tendencias.'],
      ['Grupo, factor y pruebas pretransfusionales', 'Trauma con posibilidad de sangrado significativo.', 'Preparación para transfusión.', 'En hemorragia exanguinante no retrasar sangre de emergencia por esperar compatibilidad completa si el protocolo local la contempla.'],
      ['Gasometría y lactato', 'Shock, trauma grave o insuficiencia respiratoria.', 'Acidosis, ventilación, oxigenación si arterial y marcador de hipoperfusión.', 'El lactato ayuda a estimar gravedad y tendencia, pero debe integrarse con perfusión clínica.'],
      ['Coagulograma y fibrinógeno', 'Hemorragia, trauma grave, anticoagulación o protocolo de transfusión masiva.', 'Coagulopatía y consumo.', 'Puede orientar reposición de componentes; complementar con viscoelasticidad si está disponible.'],
      ['TEG/ROTEM o prueba viscoelástica', 'Hemorragia significativa cuando está disponible.', 'Perfil dinámico de formación, fuerza y lisis del coágulo.', 'Puede guiar reposición hemostática dirigida y detectar hiperfibrinólisis.'],
      ['Electrolitos, función renal, glucosa', 'Trauma moderado/grave.', 'Alteraciones metabólicas, lesión renal, hiperpotasemia, hipoglucemia.', 'Particularmente relevantes en aplastamiento, shock y transfusión masiva.'],
      ['Calcio ionizado', 'Hemorragia importante o transfusión masiva.', 'Hipocalcemia por citrato y shock.', 'Corregir hipocalcemia significativa durante reanimación según protocolo.'],
      ['eFAST', 'Trauma toracoabdominal, especialmente inestable.', 'Líquido pericárdico, intraperitoneal y pleural, además de neumotórax según protocolo.', 'Un eFAST negativo no excluye todas las lesiones; en inestabilidad su valor es orientar decisiones rápidas.'],
      ['Radiografía de tórax portátil', 'Trauma torácico cuando el paciente lo permite y no se retrasa una intervención necesaria.', 'Neumotórax, hemotórax, lesiones óseas, mediastino y posición de dispositivos.', 'No esperar radiografía para tratar neumotórax a tensión clínicamente evidente.'],
      ['Radiografía de pelvis', 'Trauma de alta energía/inestabilidad cuando la información modifica conducta.', 'Fractura pélvica significativa.', 'En algunos centros puede omitirse si se realizará TC inmediata en un paciente estable.'],
      ['TC de cuerpo entero con contraste', 'Paciente hemodinámicamente estable o estabilizado con trauma de alta energía/politrauma y sospecha de lesiones múltiples.', 'Lesiones craneales, cervicales, torácicas, abdominales, pélvicas y vasculares según protocolo.', 'No trasladar a TC a un paciente demasiado inestable si requiere control hemorrágico/procedimiento inmediato.'],
      ['TC de cráneo', 'TCE con criterios clínicos, deterioro neurológico, anticoagulación o mecanismo de riesgo.', 'Hemorragia intracraneal, fracturas, edema y efecto de masa.', 'El deterioro con signos de herniación requiere tratamiento urgente y neurocirugía, sin demoras innecesarias.'],
      ['TC cervical', 'Trauma con criterios que impiden aclaramiento clínico seguro.', 'Fractura, alineación y lesiones óseas.', 'La decisión debe seguir reglas validadas/locales; no mantener inmovilización innecesaria indefinidamente si la columna se aclara.'],
      ['Angio-TC', 'Sospecha de lesión aórtica, vascular, sangrado activo, lesión cervical vascular o extremidad según contexto.', 'Extravasación, lesión arterial, disección, pseudoaneurisma u oclusión.', 'Puede dirigir cirugía o radiología intervencionista.'],
      ['ECG y troponina', 'Trauma torácico significativo, arritmia, dolor torácico o sospecha de lesión cardíaca.', 'Arritmias, isquemia y lesión miocárdica.', 'ECG anormal y/o troponina pueden requerir monitorización y ecocardiografía según contexto.'],
      ['Estudios específicos según lesión', 'Una vez estabilizado y según hallazgos.', 'Doppler, estudios urológicos, endoscopia, estudios oculares, RM de columna u otros.', 'No deben desplazar la prioridad de XABCDE ni retrasar control de amenazas vitales.']
    ]),
    initialTreatment: richText(
      { kind: 'heading', text: 'Principio general' },
      { kind: 'paragraph', text: 'El tratamiento sigue XABCDE y ocurre en paralelo con el diagnóstico.' },
      { kind: 'paragraph', text: 'No completar toda la evaluación antes de tratar una amenaza evidente.' },
      { kind: 'heading', text: 'X — Control de hemorragia' },
      { kind: 'paragraph', text: 'Hemorragia externa:' },
      { kind: 'bullet', items: ['compresión directa', 'vendaje compresivo', 'torniquete cuando corresponde', 'empaquetamiento de heridas', 'agentes hemostáticos según protocolo'] },
      { kind: 'paragraph', text: 'Hemorragia pélvica:' },
      { kind: 'bullet', items: ['colocar binder pélvico correctamente, habitualmente a nivel de trocánteres mayores, cuando se sospecha fractura pélvica inestable', 'evitar maniobras repetidas de compresión pélvica', 'coordinar cirugía/radiología intervencionista o packing según recursos'] },
      { kind: 'paragraph', text: 'Hemorragia interna:' },
      { kind: 'bullet', items: ['control quirúrgico o intervencionista precoz cuando el paciente permanece inestable', 'considerar estrategia de daño control'] },
      { kind: 'heading', text: 'Reanimación hemostática' },
      { kind: 'paragraph', text: 'En hemorragia grave:' },
      { kind: 'bullet', items: ['minimizar cristaloides excesivos', 'utilizar hemoderivados tempranamente', 'activar protocolo de transfusión masiva según criterios locales', 'mantener proporciones balanceadas según protocolo institucional', 'medir/corregir fibrinógeno y coagulopatía', 'monitorizar calcio', 'mantener normotermia', 'corregir acidosis mediante control del shock y perfusión'] },
      { kind: 'paragraph', text: 'La reanimación no sustituye al control definitivo de la hemorragia.' },
      { kind: 'heading', text: 'Ácido tranexámico' },
      { kind: 'paragraph', text: 'Considerar TXA en trauma con hemorragia significativa o alto riesgo de sangrado cuando se encuentra dentro de la ventana recomendada por protocolos, idealmente lo antes posible y dentro de las primeras 3 horas del trauma.' },
      { kind: 'paragraph', text: 'No administrarlo de rutina a todo traumatizado sin criterio hemorrágico.' },
      { kind: 'paragraph', text: 'Seguir dosis/protocolo institucional.' },
      { kind: 'heading', text: 'Hipotensión permisiva' },
      { kind: 'paragraph', text: 'En trauma hemorrágico sin TCE grave, puede considerarse una estrategia de presión más baja hasta lograr hemostasia definitiva, según protocolos y contexto.' },
      { kind: 'paragraph', text: 'NO aplicar hipotensión permisiva cuando existe TCE grave u otras situaciones donde la perfusión de órgano dependa de una presión adecuada.' },
      { kind: 'heading', text: 'A — Vía aérea' },
      { kind: 'paragraph', text: 'Indicaciones de vía aérea definitiva:' },
      { kind: 'bullet', items: ['apnea', 'incapacidad para proteger vía aérea', 'hipoxemia/ventilación inadecuada', 'trauma facial grave', 'deterioro neurológico', 'agotamiento', 'necesidad anticipada de procedimiento/traslado'] },
      { kind: 'paragraph', text: 'Principios:' },
      { kind: 'bullet', items: ['protección cervical razonada', 'preoxigenación', 'succión preparada', 'plan A/B/C', 'videolaringoscopia si disponible y apropiada', 'acceso quirúrgico de rescate cuando sea necesario'] },
      { kind: 'paragraph', text: 'En trauma facial/cervical con imposibilidad de intubación/oxigenación, proceder a vía aérea quirúrgica de emergencia según protocolo.' },
      { kind: 'paragraph', text: 'Anticipar hipotensión peri-intubación y preparar soporte hemodinámico.' },
      { kind: 'heading', text: 'B — Tórax' },
      { kind: 'paragraph', text: 'Neumotórax a tensión:' }, { kind: 'bullet', items: ['descompresión inmediata', 'luego drenaje torácico definitivo'] },
      { kind: 'paragraph', text: 'Neumotórax abierto:' }, { kind: 'bullet', items: ['apósito oclusivo ventilado/estrategia local apropiada', 'drenaje torácico alejado de la herida', 'reparación definitiva'] },
      { kind: 'paragraph', text: 'Hemotórax masivo:' }, { kind: 'bullet', items: ['tubo de tórax', 'reanimación', 'evaluar cirugía urgente según volumen inicial, sangrado persistente y estado fisiológico, siguiendo protocolos locales'] },
      { kind: 'paragraph', text: 'Tórax inestable/contusión:' }, { kind: 'bullet', items: ['analgesia multimodal', 'oxígeno', 'fisioterapia/expansión pulmonar', 'ventilación no invasiva o invasiva si corresponde', 'evitar intubación solo por la presencia radiológica del tórax inestable si la ventilación es adecuada'] },
      { kind: 'paragraph', text: 'Taponamiento:' }, { kind: 'bullet', items: ['descompresión/drenaje urgente', 'toracotomía de resucitación solo en indicaciones altamente seleccionadas y según capacidad local'] },
      { kind: 'heading', text: 'C — Circulación' },
      { kind: 'paragraph', text: 'Acceso:' }, { kind: 'bullet', items: ['dos vías periféricas de gran calibre cuando sea posible', 'intraóseo si acceso IV rápido no es posible', 'acceso central si aporta, sin retrasar reanimación'] },
      { kind: 'paragraph', text: 'Fluidos:' }, { kind: 'bullet', items: ['limitar cristaloides en hemorragia significativa', 'usar bolos individualizados cuando exista hipovolemia no hemorrágica o indicación específica'] },
      { kind: 'paragraph', text: 'Vasopresores:' }, { kind: 'bullet', items: ['no son tratamiento primario del shock hemorrágico', 'pueden utilizarse selectivamente cuando persiste hipotensión tras control/reanimación adecuada o en shock neurogénico', 'norepinefrina puede ser apropiada según mecanismo'] },
      { kind: 'heading', text: 'D — TCE' },
      { kind: 'paragraph', text: 'Objetivos:' }, { kind: 'bullet', items: ['evitar hipoxemia', 'evitar hipotensión', 'mantener ventilación adecuada', 'tratar convulsiones', 'elevar cabeza cuando sea seguro', 'neurocirugía precoz ante lesión quirúrgica'] },
      { kind: 'paragraph', text: 'No realizar hiperventilación profiláctica rutinaria.' },
      { kind: 'paragraph', text: 'Hiperventilación breve puede utilizarse como medida puente en deterioro agudo con signos de herniación mientras se organiza tratamiento definitivo.' },
      { kind: 'paragraph', text: 'Considerar terapia hiperosmolar según protocolo ante hipertensión intracraneal/herniación.' },
      { kind: 'paragraph', text: 'Revertir anticoagulación cuando corresponda en hemorragia intracraneal traumática.' },
      { kind: 'heading', text: 'E — Exposición / hipotermia' },
      { kind: 'paragraph', text: 'Prevenir activamente hipotermia:' }, { kind: 'bullet', items: ['mantas', 'calentamiento ambiental', 'fluidos y sangre calentados', 'minimizar exposición'] },
      { kind: 'paragraph', text: 'La combinación de hipotermia, acidosis y coagulopatía empeora drásticamente el sangrado.' },
      { kind: 'heading', text: 'Lesiones específicas' },
      { kind: 'paragraph', text: 'Fracturas abiertas:' }, { kind: 'bullet', items: ['cubrir con apósito estéril', 'controlar hemorragia', 'inmovilizar', 'antibióticos tempranos según protocolo', 'profilaxis antitetánica', 'valoración traumatológica', 'desbridamiento quirúrgico según lesión'] },
      { kind: 'paragraph', text: 'Lesión vascular de extremidad. Signos duros:' }, { kind: 'bullet', items: ['hemorragia pulsátil', 'hematoma expansivo', 'ausencia de pulso/isquemia', 'soplo/frémito', 'sangrado no controlable'] },
      { kind: 'paragraph', text: 'Con signos duros y compromiso, coordinar cirugía vascular urgente sin demoras diagnósticas innecesarias.' },
      { kind: 'paragraph', text: 'Síndrome compartimental:' }, { kind: 'bullet', items: ['alta sospecha clínica', 'medir presiones si el diagnóstico es incierto', 'fasciotomía urgente cuando está indicado'] },
      { kind: 'paragraph', text: 'Aplastamiento / rabdomiólisis:' }, { kind: 'bullet', items: ['monitorizar potasio, función renal y ECG', 'fluidoterapia según contexto', 'tratar hiperpotasemia inmediatamente', 'vigilar síndrome compartimental'] },
      { kind: 'paragraph', text: 'Trauma en embarazo:' }, { kind: 'bullet', items: ['prioridad inicial: estabilización materna', 'desplazamiento uterino lateral/posición adecuada desde gestación avanzada si corresponde', 'evaluación obstétrica y fetal tras estabilización', 'administrar inmunoglobulina anti-D en gestantes Rh negativas según indicaciones locales', 'considerar hemorragia fetomaterna y desprendimiento placentario'] }
    ),
    reassessment: richText(
      { kind: 'paragraph', text: 'Repetir XABCDE después de:' },
      { kind: 'bullet', items: ['intubación', 'descompresión torácica', 'colocación de tubo de tórax', 'control hemorrágico', 'fluidos/transfusión', 'estabilización pélvica', 'procedimiento', 'traslado entre áreas', 'cualquier deterioro'] },
      { kind: 'paragraph', text: 'Reevaluar:' },
      { kind: 'bullet', items: ['sangrado activo', 'PA/PAM', 'FC', 'perfusión', 'relleno capilar', 'temperatura', 'estado mental', 'Glasgow', 'pupilas', 'SpO2', 'ventilación', 'auscultación', 'drenajes torácicos', 'abdomen', 'pelvis', 'pulsos distales', 'diuresis', 'lactato', 'hemoglobina', 'coagulación', 'calcio', 'temperatura corporal', 'respuesta transfusional'] },
      { kind: 'paragraph', text: 'Preguntas clave:' },
      { kind: 'bullet', items: ['¿La hemorragia está controlada?', '¿La vía aérea sigue segura?', '¿La ventilación es adecuada?', '¿Apareció una nueva lesión torácica?', '¿La perfusión mejoró?', '¿Sigue necesitando transfusión?', '¿Existe hemorragia oculta no identificada?', '¿El Glasgow cambió?', '¿Se desarrolló coagulopatía?', '¿Está hipotérmico?', '¿Necesita cirugía/radiología intervencionista?', '¿Es seguro realizar TC?', '¿Hay nuevas lesiones en la evaluación secundaria?'] }
    ),
    disposition: {
      discharge: richText({ kind: 'paragraph', text: 'El politrauma real o trauma mayor no es candidato a alta durante la fase inicial.' }, { kind: 'paragraph', text: 'El alta solo puede considerarse si, tras evaluación completa y observación cuando corresponda:' }, { kind: 'bullet', items: ['se descartan lesiones significativas', 'el paciente permanece hemodinámicamente estable', 'no hay deterioro neurológico', 'dolor controlable', 'marcha/tolerancia adecuadas según lesión', 'seguimiento seguro', 'pautas de alarma comprendidas'] }),
      admission: richText({ kind: 'paragraph', text: 'Indicar internación ante:' }, { kind: 'bullet', items: ['lesiones que requieren observación', 'fracturas relevantes', 'TCE con factores de riesgo', 'contusión pulmonar', 'dolor no controlado', 'necesidad de cirugía diferida', 'anemia/sangrado estable', 'comorbilidades o fragilidad', 'imposibilidad de seguimiento seguro'] }),
      criticalCare: richText({ kind: 'paragraph', text: 'Indicar área crítica/UCI ante:' }, { kind: 'bullet', items: ['shock', 'transfusión masiva', 'ventilación invasiva', 'TCE grave', 'lesión torácica grave', 'hemorragia activa', 'necesidad de vasopresores', 'cirugía de daño control', 'falla orgánica', 'deterioro rápido', 'hipotermia significativa', 'necesidad de monitorización continua'] }),
      referral: richText({ kind: 'paragraph', text: 'Según lesiones:' }, { kind: 'bullet', items: ['cirugía general', 'traumatología', 'neurocirugía', 'cirugía vascular', 'cirugía cardiovascular/torácica', 'radiología intervencionista', 'terapia intensiva', 'obstetricia', 'urología', 'oftalmología', 'cirugía plástica/maxilofacial', 'centro de quemados'] }, { kind: 'paragraph', text: 'Transferir a centro de trauma de mayor complejidad cuando los recursos definitivos no estén disponibles.' }, { kind: 'paragraph', text: 'No retrasar intervenciones salvadoras por organizar el traslado.' })
    },
    warningsAndInstructions: richText({ kind: 'paragraph', text: 'Si el paciente finalmente puede manejarse ambulatoriamente, indicar retorno inmediato ante:' }, { kind: 'bullet', items: ['pérdida de conciencia', 'confusión', 'somnolencia creciente', 'vómitos repetidos', 'cefalea progresiva', 'convulsiones', 'debilidad o parestesias', 'disnea', 'dolor torácico', 'hemoptisis', 'dolor abdominal progresivo', 'distensión abdominal', 'sangrado', 'mareos/síncope', 'palidez marcada', 'fiebre', 'dolor desproporcionado en extremidad', 'frialdad o cambio de color distal', 'disminución de pulsos', 'incapacidad para movilizar una extremidad', 'empeoramiento general'] }),
    commonErrors: richText({ kind: 'bullet', items: ['Seguir ABCDE sin controlar primero una hemorragia externa exanguinante.', 'Esperar una radiografía para tratar un neumotórax a tensión clínicamente evidente.', 'Trasladar a TC a un paciente demasiado inestable.', 'Administrar grandes volúmenes de cristaloides en shock hemorrágico.', 'Retrasar hemoderivados y control del sangrado.', 'Usar vasopresores como sustituto de la hemostasia.', 'No prevenir hipotermia desde el comienzo.', 'Olvidar monitorizar y corregir hipocalcemia durante transfusión masiva.', 'No considerar TXA temprano cuando está indicado.', 'Aplicar hipotensión permisiva en TCE grave.', 'Atribuir alteración del sensorio a alcohol sin excluir TCE, hipoxia o shock.', 'Repetir maniobras de compresión pélvica.', 'Colocar incorrectamente el binder pélvico demasiado alto.', 'Introducir sonda uretral a ciegas ante signos de lesión uretral.', 'No reevaluar XABCDE después de una intervención.', 'Confiar en una hemoglobina inicial normal para descartar hemorragia.', 'Dar por negativo un trauma abdominal solo por eFAST negativo.', 'No examinar dorso, periné y extremidades tras estabilización.', 'No documentar hora de colocación de torniquete.', 'Buscar un diagnóstico anatómico perfecto antes de tratar una amenaza fisiológica evidente.'] }),
    clinicalPearls: richText({ kind: 'bullet', items: ['En trauma grave, primero se trata la fisiología que mata, después se completa la anatomía.', 'XABCDE recuerda que una hemorragia exanguinante puede preceder a la vía aérea.', 'Un paciente traumatizado puede sangrar mucho antes de volverse hipotenso.', 'La hemoglobina inicial puede ser engañosamente normal.', 'Tórax, abdomen, pelvis y huesos largos son reservorios clásicos de hemorragia oculta.', 'Un torniquete bien indicado salva vidas; documentar la hora.', 'El binder pélvico debe colocarse sobre los trocánteres mayores.', 'En shock hemorrágico, hemostasia y sangre son más importantes que litros de cristaloides.', 'TXA es tiempo-dependiente y debe utilizarse cuando existe indicación hemorrágica, no de rutina.', 'Hipotermia, acidosis y coagulopatía se potencian entre sí.', 'El calcio importa durante transfusión masiva.', 'En TCE grave, una sola hipotensión puede empeorar el pronóstico.', 'Neumotórax a tensión es un diagnóstico que puede ser clínico y terapéutico.', 'eFAST positivo en inestable puede acelerar cirugía; eFAST negativo no descarta todas las lesiones.', 'La TC es para el paciente suficientemente estable para llegar a ella.', 'Repetir XABCDE detecta lesiones que aparecieron o se hicieron evidentes tras la reanimación.', 'El alcohol no protege contra el trauma ni explica por sí solo un Glasgow bajo.', 'Una extremidad con pulso puede tener lesión vascular; interpretar todo el examen.', 'En embarazo traumatizado, la mejor reanimación fetal comienza por estabilizar a la madre.', 'El trauma mayor requiere trabajo simultáneo: reanimación, diagnóstico, hemostasia y planificación definitiva.'] })
  };
}

const polytraumaDecisionTree: DecisionTree = {
  rootNodeId: 'polytrauma-n01',
  nodes: [
    { id: 'polytrauma-n01', type: 'start', title: 'Paciente con trauma potencialmente grave', description: 'Iniciar evaluación primaria XABCDE, tratando inmediatamente cualquier amenaza vital identificada.' },
    { id: 'polytrauma-n02', type: 'question', title: 'X: ¿Existe hemorragia externa exanguinante?', description: 'Buscar sangrado masivo, amputación, herida penetrante o hemorragia de extremidad/zona de unión.' },
    { id: 'polytrauma-n03', type: 'action', title: 'Control inmediato de la hemorragia', description: 'Compresión, vendaje, torniquete o empaquetamiento según localización; documentar hora del torniquete.' },
    { id: 'polytrauma-n04', type: 'question', title: 'A: ¿La vía aérea está amenazada?', description: 'Evaluar voz, obstrucción, sangre/vómitos, trauma facial/cervical, nivel de conciencia y capacidad para protegerla.' },
    { id: 'polytrauma-n05', type: 'action', title: 'Asegurar vía aérea con protección cervical', description: 'Preoxigenar, preparar succión y rescate, anticipar hipotensión peri-intubación y mantener precauciones cervicales razonadas.' },
    { id: 'polytrauma-n06', type: 'question', title: 'B: ¿Hay deterioro respiratorio o lesión torácica letal?', description: 'Buscar asimetría, hipoxemia, heridas abiertas, ausencia de murmullo, shock obstructivo y signos de hemotórax.' },
    { id: 'polytrauma-n07', type: 'question', title: '¿Neumotórax a tensión probable?', description: 'Paciente inestable con deterioro respiratorio/hemodinámico y hallazgos compatibles.' },
    { id: 'polytrauma-n08', type: 'action', title: 'Descompresión inmediata', description: 'No esperar imagen si la sospecha clínica es alta; completar drenaje torácico definitivo.' },
    { id: 'polytrauma-n09', type: 'question', title: '¿Neumotórax abierto?', description: 'Buscar herida torácica comunicante con alteración ventilatoria.' },
    { id: 'polytrauma-n10', type: 'action', title: 'Tratar herida y drenar tórax', description: 'Aplicar estrategia oclusiva apropiada y colocar drenaje torácico según protocolo.' },
    { id: 'polytrauma-n11', type: 'question', title: '¿Hemotórax masivo?', description: 'Sospechar ante shock, disminución marcada del murmullo y sangre pleural significativa.' },
    { id: 'polytrauma-n12', type: 'action', title: 'Drenaje, reanimación y cirugía según respuesta', description: 'Colocar drenaje torácico, iniciar reanimación hemostática y valorar cirugía urgente según fisiología y sangrado.' },
    { id: 'polytrauma-n13', type: 'question', title: '¿Taponamiento cardíaco probable?', description: 'Integrar mecanismo, shock y POCUS/ecocardiografía cuando esté disponible.' },
    { id: 'polytrauma-n14', type: 'action', title: 'Descompresión/drenaje pericárdico urgente', description: 'Sostener perfusión mientras se organiza tratamiento definitivo.' },
    { id: 'polytrauma-n15', type: 'action', title: 'Continuar soporte respiratorio y reevaluar B', description: 'Oxígeno, analgesia y soporte ventilatorio según lesión y fisiología.' },
    { id: 'polytrauma-n16', type: 'question', title: 'C: ¿Existe shock o hipoperfusión?', description: 'Evaluar PA/PAM, pulsos, relleno capilar, piel, estado mental, diuresis y respuesta a intervenciones.' },
    { id: 'polytrauma-n17', type: 'question', title: '¿Hemorragia interna u oculta probable?', description: 'Buscar tórax, abdomen, pelvis/retroperitoneo y huesos largos como fuentes principales.' },
    { id: 'polytrauma-n18', type: 'action', title: 'Reanimación hemostática', description: 'Priorizar hemoderivados, protocolo de hemorragia masiva cuando corresponda, calcio, temperatura y corrección dirigida de coagulopatía.' },
    { id: 'polytrauma-n19', type: 'question', title: '¿Fractura pélvica hemorrágica probable?', description: 'Trauma de alta energía, dolor/deformidad pélvica y shock sin otra fuente evidente.' },
    { id: 'polytrauma-n20', type: 'action', title: 'Binder pélvico y control definitivo', description: 'Colocar binder a nivel de trocánteres mayores y coordinar packing, cirugía o embolización según recursos.' },
    { id: 'polytrauma-n21', type: 'question', title: '¿Paciente hemodinámicamente inestable pese a reanimación?', description: 'Determinar si persiste shock o necesidad transfusional y si requiere control inmediato de hemorragia.' },
    { id: 'polytrauma-n22', type: 'action', title: 'Control hemorrágico urgente / daño control', description: 'Priorizar quirófano, radiología intervencionista u otra estrategia definitiva según fuente y recursos; no retrasar por TC no esencial.' },
    { id: 'polytrauma-n23', type: 'question', title: 'D: ¿TCE grave o deterioro neurológico?', description: 'Evaluar Glasgow, pupilas, focalidad, convulsiones y tendencia neurológica.' },
    { id: 'polytrauma-n24', type: 'action', title: 'Prevenir lesión cerebral secundaria', description: 'Evitar hipoxia e hipotensión, mantener ventilación apropiada y coordinar neuroimagen/neurocirugía según estabilidad.' },
    { id: 'polytrauma-n25', type: 'question', title: '¿Signos de herniación cerebral?', description: 'Deterioro rápido, anisocoria, posturas anormales u otros signos compatibles.' },
    { id: 'polytrauma-n26', type: 'action', title: 'Medidas puente y neurocirugía urgente', description: 'Aplicar terapia hiperosmolar y medidas temporales según protocolo mientras se organiza tratamiento definitivo; evitar hiperventilación profiláctica rutinaria.' },
    { id: 'polytrauma-n27', type: 'action', title: 'E: Exposición completa y prevención de hipotermia', description: 'Examinar completamente, incluyendo dorso/periné/extremidades, y calentar activamente al paciente.' },
    { id: 'polytrauma-n28', type: 'question', title: '¿Hay lesión vascular de extremidad o síndrome compartimental?', description: 'Buscar hemorragia pulsátil, hematoma expansivo, isquemia, ausencia de pulso o dolor desproporcionado.' },
    { id: 'polytrauma-n29', type: 'action', title: 'Tratamiento vascular/quirúrgico urgente', description: 'Coordinar cirugía vascular o fasciotomía según lesión, sin retrasos diagnósticos innecesarios ante signos duros.' },
    { id: 'polytrauma-n30', type: 'question', title: '¿Está suficientemente estable para estudios avanzados?', description: 'Reevaluar hemodinamia, ventilación, sangrado y neurología antes de trasladar fuera del área de reanimación.' },
    { id: 'polytrauma-n31', type: 'action', title: 'TC/estudios dirigidos y evaluación secundaria', description: 'En paciente estable o estabilizado, completar imágenes y examen secundario según mecanismo y hallazgos.' },
    { id: 'polytrauma-n32', type: 'warning', title: 'No trasladar a TC al paciente inestable', description: 'Si persiste inestabilidad, priorizar diagnóstico al lado de la cama y tratamiento definitivo de la causa antes de estudios demorados.' },
    { id: 'polytrauma-n33', type: 'question', title: '¿Persiste deterioro o aparece una nueva amenaza?', description: 'Repetir XABCDE y reconsiderar hemorragia oculta, lesión torácica, TCE, shock mixto y lesiones inicialmente no evidentes.' },
    { id: 'polytrauma-n34', type: 'disposition', title: 'Definir destino y tratamiento definitivo', description: 'Determinar UCI, quirófano, intervencionismo, internación, observación o derivación a centro de trauma según lesiones, fisiología y recursos.' }
  ],
  edges: [
    { id: 'polytrauma-e01', from: 'polytrauma-n01', to: 'polytrauma-n02', label: 'Iniciar XABCDE' },
    { id: 'polytrauma-e02', from: 'polytrauma-n02', to: 'polytrauma-n03', label: 'Sí' },
    { id: 'polytrauma-e03', from: 'polytrauma-n02', to: 'polytrauma-n04', label: 'No' },
    { id: 'polytrauma-e04', from: 'polytrauma-n03', to: 'polytrauma-n04', label: 'Hemorragia controlada inicialmente' },
    { id: 'polytrauma-e05', from: 'polytrauma-n04', to: 'polytrauma-n05', label: 'Sí' },
    { id: 'polytrauma-e06', from: 'polytrauma-n04', to: 'polytrauma-n06', label: 'No' },
    { id: 'polytrauma-e07', from: 'polytrauma-n05', to: 'polytrauma-n06', label: 'Continuar' },
    { id: 'polytrauma-e08', from: 'polytrauma-n06', to: 'polytrauma-n07', label: 'Evaluar lesiones torácicas' },
    { id: 'polytrauma-e09', from: 'polytrauma-n07', to: 'polytrauma-n08', label: 'Sí' },
    { id: 'polytrauma-e10', from: 'polytrauma-n07', to: 'polytrauma-n09', label: 'No' },
    { id: 'polytrauma-e11', from: 'polytrauma-n08', to: 'polytrauma-n15', label: 'Tras descompresión' },
    { id: 'polytrauma-e12', from: 'polytrauma-n09', to: 'polytrauma-n10', label: 'Sí' },
    { id: 'polytrauma-e13', from: 'polytrauma-n09', to: 'polytrauma-n11', label: 'No' },
    { id: 'polytrauma-e14', from: 'polytrauma-n10', to: 'polytrauma-n15', label: 'Tras tratamiento' },
    { id: 'polytrauma-e15', from: 'polytrauma-n11', to: 'polytrauma-n12', label: 'Sí' },
    { id: 'polytrauma-e16', from: 'polytrauma-n11', to: 'polytrauma-n13', label: 'No' },
    { id: 'polytrauma-e17', from: 'polytrauma-n12', to: 'polytrauma-n15', label: 'Continuar reanimación' },
    { id: 'polytrauma-e18', from: 'polytrauma-n13', to: 'polytrauma-n14', label: 'Sí' },
    { id: 'polytrauma-e19', from: 'polytrauma-n13', to: 'polytrauma-n15', label: 'No' },
    { id: 'polytrauma-e20', from: 'polytrauma-n14', to: 'polytrauma-n15', label: 'Tras intervención' },
    { id: 'polytrauma-e21', from: 'polytrauma-n15', to: 'polytrauma-n16', label: 'Continuar a C' },
    { id: 'polytrauma-e22', from: 'polytrauma-n16', to: 'polytrauma-n17', label: 'Buscar hemorragia' },
    { id: 'polytrauma-e23', from: 'polytrauma-n17', to: 'polytrauma-n18', label: 'Sí o no puede excluirse' },
    { id: 'polytrauma-e24', from: 'polytrauma-n17', to: 'polytrauma-n23', label: 'No' },
    { id: 'polytrauma-e25', from: 'polytrauma-n18', to: 'polytrauma-n19', label: 'Buscar fuente' },
    { id: 'polytrauma-e26', from: 'polytrauma-n19', to: 'polytrauma-n20', label: 'Sí' },
    { id: 'polytrauma-e27', from: 'polytrauma-n19', to: 'polytrauma-n21', label: 'No' },
    { id: 'polytrauma-e28', from: 'polytrauma-n20', to: 'polytrauma-n21', label: 'Reevaluar' },
    { id: 'polytrauma-e29', from: 'polytrauma-n21', to: 'polytrauma-n22', label: 'Sí' },
    { id: 'polytrauma-e30', from: 'polytrauma-n21', to: 'polytrauma-n23', label: 'No / estabilizado' },
    { id: 'polytrauma-e31', from: 'polytrauma-n22', to: 'polytrauma-n23', label: 'Tras control inicial' },
    { id: 'polytrauma-e32', from: 'polytrauma-n23', to: 'polytrauma-n24', label: 'Evaluar y proteger neurología' },
    { id: 'polytrauma-e33', from: 'polytrauma-n24', to: 'polytrauma-n25', label: 'Evaluar herniación' },
    { id: 'polytrauma-e34', from: 'polytrauma-n25', to: 'polytrauma-n26', label: 'Sí' },
    { id: 'polytrauma-e35', from: 'polytrauma-n25', to: 'polytrauma-n27', label: 'No' },
    { id: 'polytrauma-e36', from: 'polytrauma-n26', to: 'polytrauma-n27', label: 'Continuar' },
    { id: 'polytrauma-e37', from: 'polytrauma-n27', to: 'polytrauma-n28', label: 'Completar exposición' },
    { id: 'polytrauma-e38', from: 'polytrauma-n28', to: 'polytrauma-n29', label: 'Sí' },
    { id: 'polytrauma-e39', from: 'polytrauma-n28', to: 'polytrauma-n30', label: 'No' },
    { id: 'polytrauma-e40', from: 'polytrauma-n29', to: 'polytrauma-n30', label: 'Tras tratamiento inicial' },
    { id: 'polytrauma-e41', from: 'polytrauma-n30', to: 'polytrauma-n31', label: 'Sí' },
    { id: 'polytrauma-e42', from: 'polytrauma-n30', to: 'polytrauma-n32', label: 'No' },
    { id: 'polytrauma-e43', from: 'polytrauma-n31', to: 'polytrauma-n33', label: 'Tras estudios/evaluación secundaria' },
    { id: 'polytrauma-e44', from: 'polytrauma-n32', to: 'polytrauma-n33', label: 'Continuar reanimación' },
    { id: 'polytrauma-e45', from: 'polytrauma-n33', to: 'polytrauma-n34', label: 'No / estabilizado' }
  ]
};

export function createPolytraumaClinicalApproach(userId: string): ClinicalApproach {
  const timestamp = new Date().toISOString();
  const content: ClinicalApproachContent = {
    ...createPolytraumaApproachBaseContent(),
    decisionTree: polytraumaDecisionTree,
    relatedContent: []
  };
  const validation = validateDecisionTree(content.decisionTree);
  if (validation.errors.length > 0 || validation.warnings.length > 0) {
    const issues = [...validation.errors, ...validation.warnings].map((issue) => issue.message).join(' ');
    throw new Error(`El fixture de Politrauma contiene un árbol inválido: ${issues}`);
  }
  return {
    id: crypto.randomUUID(), userId,
    title: POLYTRAUMA_APPROACH_TITLE,
    description: POLYTRAUMA_APPROACH_DESCRIPTION,
    categoryId: null, category: null, content,
    createdAt: timestamp, updatedAt: timestamp, status: 'complete'
  };
}
